-- Graecia Lernapp Supabase schema
-- Run this whole file in the Supabase SQL editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar text not null default '🦉',
  created_at timestamptz not null default now()
);

create table if not exists public.chapter_progress (
  user_id bigint not null references public.users(id) on delete cascade,
  chapter_id text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'done')),
  progress double precision not null default 0 check (progress >= 0 and progress <= 1),
  started_at bigint,
  completed_at bigint,
  last_mode text,
  primary key (user_id, chapter_id)
);

create table if not exists public.mode_progress (
  user_id bigint not null references public.users(id) on delete cascade,
  chapter_id text not null,
  mode_id text not null,
  best_score double precision not null default 0 check (best_score >= 0 and best_score <= 1),
  attempts integer not null default 0 check (attempts >= 0),
  last_at bigint,
  primary key (user_id, chapter_id, mode_id)
);

create table if not exists public.item_stats (
  user_id bigint not null references public.users(id) on delete cascade,
  item_id text not null,
  correct integer not null default 0 check (correct >= 0),
  wrong integer not null default 0 check (wrong >= 0),
  streak integer not null default 0 check (streak >= 0),
  last_at bigint,
  primary key (user_id, item_id)
);

create table if not exists public.game (
  user_id bigint primary key references public.users(id) on delete cascade,
  xp integer not null default 0 check (xp >= 0),
  streak_days integer not null default 0 check (streak_days >= 0),
  last_day text,
  total_correct integer not null default 0 check (total_correct >= 0),
  total_answers integer not null default 0 check (total_answers >= 0)
);

create table if not exists public.achievements (
  user_id bigint not null references public.users(id) on delete cascade,
  id text not null,
  unlocked_at bigint not null,
  primary key (user_id, id)
);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  points integer not null check (points >= 0),
  total integer not null check (total > 0),
  grade text not null,
  at bigint not null
);

create index if not exists chapter_progress_user_idx on public.chapter_progress(user_id);
create index if not exists mode_progress_user_chapter_idx on public.mode_progress(user_id, chapter_id);
create index if not exists item_stats_user_idx on public.item_stats(user_id);
create index if not exists achievements_user_idx on public.achievements(user_id);
create index if not exists exam_results_user_at_idx on public.exam_results(user_id, at desc);

alter table public.users enable row level security;
alter table public.chapter_progress enable row level security;
alter table public.mode_progress enable row level security;
alter table public.item_stats enable row level security;
alter table public.game enable row level security;
alter table public.achievements enable row level security;
alter table public.exam_results enable row level security;

drop policy if exists "shared profiles read" on public.users;
drop policy if exists "shared profiles insert" on public.users;
drop policy if exists "shared profiles update" on public.users;
drop policy if exists "shared profiles delete" on public.users;
create policy "shared profiles read" on public.users for select to anon, authenticated using (true);
create policy "shared profiles insert" on public.users for insert to anon, authenticated with check (true);
create policy "shared profiles update" on public.users for update to anon, authenticated using (true) with check (true);
create policy "shared profiles delete" on public.users for delete to anon, authenticated using (true);

drop policy if exists "shared chapter progress read" on public.chapter_progress;
drop policy if exists "shared chapter progress insert" on public.chapter_progress;
drop policy if exists "shared chapter progress update" on public.chapter_progress;
drop policy if exists "shared chapter progress delete" on public.chapter_progress;
create policy "shared chapter progress read" on public.chapter_progress for select to anon, authenticated using (true);
create policy "shared chapter progress insert" on public.chapter_progress for insert to anon, authenticated with check (true);
create policy "shared chapter progress update" on public.chapter_progress for update to anon, authenticated using (true) with check (true);
create policy "shared chapter progress delete" on public.chapter_progress for delete to anon, authenticated using (true);

drop policy if exists "shared mode progress read" on public.mode_progress;
drop policy if exists "shared mode progress insert" on public.mode_progress;
drop policy if exists "shared mode progress update" on public.mode_progress;
drop policy if exists "shared mode progress delete" on public.mode_progress;
create policy "shared mode progress read" on public.mode_progress for select to anon, authenticated using (true);
create policy "shared mode progress insert" on public.mode_progress for insert to anon, authenticated with check (true);
create policy "shared mode progress update" on public.mode_progress for update to anon, authenticated using (true) with check (true);
create policy "shared mode progress delete" on public.mode_progress for delete to anon, authenticated using (true);

drop policy if exists "shared item stats read" on public.item_stats;
drop policy if exists "shared item stats insert" on public.item_stats;
drop policy if exists "shared item stats update" on public.item_stats;
drop policy if exists "shared item stats delete" on public.item_stats;
create policy "shared item stats read" on public.item_stats for select to anon, authenticated using (true);
create policy "shared item stats insert" on public.item_stats for insert to anon, authenticated with check (true);
create policy "shared item stats update" on public.item_stats for update to anon, authenticated using (true) with check (true);
create policy "shared item stats delete" on public.item_stats for delete to anon, authenticated using (true);

drop policy if exists "shared game read" on public.game;
drop policy if exists "shared game insert" on public.game;
drop policy if exists "shared game update" on public.game;
drop policy if exists "shared game delete" on public.game;
create policy "shared game read" on public.game for select to anon, authenticated using (true);
create policy "shared game insert" on public.game for insert to anon, authenticated with check (true);
create policy "shared game update" on public.game for update to anon, authenticated using (true) with check (true);
create policy "shared game delete" on public.game for delete to anon, authenticated using (true);

drop policy if exists "shared achievements read" on public.achievements;
drop policy if exists "shared achievements insert" on public.achievements;
drop policy if exists "shared achievements update" on public.achievements;
drop policy if exists "shared achievements delete" on public.achievements;
create policy "shared achievements read" on public.achievements for select to anon, authenticated using (true);
create policy "shared achievements insert" on public.achievements for insert to anon, authenticated with check (true);
create policy "shared achievements update" on public.achievements for update to anon, authenticated using (true) with check (true);
create policy "shared achievements delete" on public.achievements for delete to anon, authenticated using (true);

drop policy if exists "shared exam results read" on public.exam_results;
drop policy if exists "shared exam results insert" on public.exam_results;
drop policy if exists "shared exam results update" on public.exam_results;
drop policy if exists "shared exam results delete" on public.exam_results;
create policy "shared exam results read" on public.exam_results for select to anon, authenticated using (true);
create policy "shared exam results insert" on public.exam_results for insert to anon, authenticated with check (true);
create policy "shared exam results update" on public.exam_results for update to anon, authenticated using (true) with check (true);
create policy "shared exam results delete" on public.exam_results for delete to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;
