import type { MCQuestion } from './types'

// Multiple-choice bank (1 or more correct). Tagged by chapter via the `chapter` map below.
// correct = array of indices.

export interface TaggedMC extends MCQuestion {
  chapter: string
}

export const MC_QUESTIONS: TaggedMC[] = [
  // ——— Alphabet & Geschichte ———
  {
    id: 'mc-alpha-1', chapter: 'alphabet',
    q: 'Wie viele Buchstaben hat das griechische Alphabet?',
    options: ['22 Buchstaben', '24 Buchstaben', '27 Buchstaben', '26 Buchstaben'],
    correct: [1],
    explain: '24 Buchstaben: 7 Vokale und 17 Konsonanten.',
  },
  {
    id: 'mc-alpha-2', chapter: 'alphabet',
    q: 'Welche Aussagen zur Entstehung des griechischen Alphabets sind richtig?',
    options: [
      'Es wurde von den Phöniziern übernommen (22 Konsonanten).',
      'Die Griechen führten Vokalzeichen ein.',
      'Es entstand direkt aus Linear A.',
      'Standardisierung 403 v. Chr. in Athen unter Eukleides.',
    ],
    correct: [0, 1, 3],
    explain: 'Das Alphabet kam über die Phönizier; die Griechen ergänzten Vokale. Standardisiert 403 v. Chr. unter Eukleides. Es stammt NICHT direkt aus Linear A (das war eine minoische Silben-/Schriftform).',
  },
  {
    id: 'mc-alpha-3', chapter: 'alphabet',
    q: 'Was war Linearschrift B?',
    options: [
      'Eine mykenische Silbenschrift mit ~80 Zeichen',
      'Hauptsächlich für ökonomische Buchführung genutzt',
      'Das fertige griechische Alphabet',
      'Bis heute nicht entziffert',
    ],
    correct: [0, 1],
    explain: 'Linear B = mykenische Silbenschrift (~80 Zeichen), v.a. Buchführung. Nicht entziffert ist Linear A. Linear B ist kein Alphabet.',
  },
  {
    id: 'mc-alpha-4', chapter: 'alphabet',
    q: 'Ordne die Epochen zeitlich richtig zu: Welche kam zuerst?',
    options: ['Klassische Zeit', 'Dunkle Jahrhunderte', 'Hellenistische Zeit', 'Archaische Zeit'],
    correct: [1],
    explain: 'Reihenfolge: Mykenisch → Dunkle Jahrhunderte (1200–800) → Archaisch → Klassisch → Hellenistisch.',
  },

  // ——— Transkription ———
  {
    id: 'mc-tr-1', chapter: 'transkription',
    q: 'Wie wird η (Eta) transkribiert?',
    options: ['e', 'ē (langes e)', 'h', 'ä'],
    correct: [1],
    explain: 'η = ē. Das Makron kennzeichnet den langen Vokal (Gegensatz: ε = e).',
  },
  {
    id: 'mc-tr-2', chapter: 'transkription',
    q: 'Welche Transkriptionen sind korrekt?',
    options: ['ω = ō', 'θ = th', 'χ = ch', 'φ = f'],
    correct: [0, 1, 2],
    explain: 'ω = ō, θ = th, χ = ch. φ wird als „ph" transkribiert, nicht „f".',
  },
  {
    id: 'mc-tr-3', chapter: 'transkription',
    q: 'Was bewirkt ein Spiritus asper (῾)?',
    options: [
      'Er wird mit „h" transkribiert',
      'Er steht am Wortanfang über dem ersten Vokal',
      'Er zeigt an, dass keine Behauchung vorliegt',
      'Bei Diphthongen steht er über dem zweiten Vokal',
    ],
    correct: [0, 1, 3],
    explain: 'Der asper = Behauchung → „h", am Wortanfang über dem 1. Vokal (bei Diphthongen über dem 2.). „Keine Behauchung" ist der Spiritus lenis.',
  },
  {
    id: 'mc-tr-4', chapter: 'transkription',
    q: 'Wie wird das υ in den Diphthongen αυ, ευ, ου transkribiert?',
    options: ['als y', 'als u', 'als v', 'als ü'],
    correct: [1],
    explain: 'υ-Diphthonge: αυ→au, ευ→eu, ου→ou. Ausnahme: υι → yi.',
  },
  {
    id: 'mc-tr-5', chapter: 'transkription',
    q: 'Wie wird ἀνάγκη korrekt transkribiert?',
    options: ['anágkē', 'anánkē', 'anánkä', 'ananke'],
    correct: [1],
    explain: 'γ vor Guttural (hier κ) wird nasaliert → „n": anánkē. Außerdem η = ē.',
  },
  {
    id: 'mc-tr-6', chapter: 'transkription',
    q: 'Warum wird ῥυθμός als „rhythmós" transkribiert?',
    options: [
      'ρ am Wortanfang ist immer behaucht → rh',
      'υ wird hier zu y',
      'Wegen γ vor Guttural',
      'Weil das Wort einen Akut trägt',
    ],
    correct: [0, 1],
    explain: 'ρ am Wortanfang → „rh"; das υ (kein Diphthong) bleibt „y" → rhythmós.',
  },
  {
    id: 'mc-tr-7', chapter: 'transkription',
    q: 'Für welche Transkriptionsrichtung müssen Akzente gesetzt werden?',
    options: [
      'griechisch → lateinisch (Akzente nötig)',
      'lateinisch → griechisch (Akzente nötig)',
      'für beide Richtungen',
      'für keine Richtung',
    ],
    correct: [1],
    explain: 'lat. → griech.: Akzente notwendig. griech. → lat.: Akzente nicht notwendig.',
  },

  // ——— Diakritika ———
  {
    id: 'mc-dia-1', chapter: 'diakritika',
    q: 'Welche Zeichen sind Akzente?',
    options: ['Akut ´', 'Gravis `', 'Spiritus asper ῾', 'Zirkumflex ῀'],
    correct: [0, 1, 3],
    explain: 'Akzente: Akut, Gravis, Zirkumflex. Der Spiritus (asper/lenis) ist kein Akzent.',
  },
  {
    id: 'mc-dia-2', chapter: 'diakritika',
    q: 'Was bedeutet ein „;" in einem griechischen Text?',
    options: ['Einen Strichpunkt', 'Ein Fragezeichen', 'Einen Doppelpunkt', 'Ein Ausrufezeichen'],
    correct: [1],
    explain: 'Das griechische „;" entspricht dem deutschen Fragezeichen.',
  },
  {
    id: 'mc-dia-3', chapter: 'diakritika',
    q: 'Wofür steht ein Punkt in der Zeilenmitte (·)?',
    options: ['Komma', 'Doppelpunkt oder Strichpunkt', 'Fragezeichen', 'Punkt am Satzende'],
    correct: [1],
    explain: 'Der Hochpunkt · steht für einen Doppelpunkt oder Strichpunkt.',
  },

  // ——— Zitierweisen ———
  {
    id: 'mc-cit-1', chapter: 'zitierweise',
    q: 'Nach welcher Ausgabe werden die Vorsokratiker zitiert?',
    options: ['Stephanus', 'Diels-Kranz', 'Bekker', 'Burnet'],
    correct: [1],
    explain: 'Vorsokratiker → Diels-Kranz (D-K), maßgeblich 5. Aufl. 1935.',
  },
  {
    id: 'mc-cit-2', chapter: 'zitierweise',
    q: 'In „D-K 22 B 3": Was bedeutet „B"?',
    options: ['Testimonium (Bericht)', 'Fragment (Originalzitat)', 'Buch 2', 'unecht zugeschrieben'],
    correct: [1],
    explain: 'B = Fragment (Originalzitat). A = Testimonium. C = unecht.',
  },
  {
    id: 'mc-cit-3', chapter: 'zitierweise',
    q: 'Welche Philosophen-Nummern stimmen?',
    options: ['22 = Heraklit', '28 = Parmenides', '11 = Thales', '59 = Pythagoras'],
    correct: [0, 1, 2],
    explain: '22 Heraklit, 28 Parmenides, 11 Thales. Pythagoras = 14; 59 = Anaxagoras.',
  },
  {
    id: 'mc-cit-4', chapter: 'zitierweise',
    q: 'Warum muss bei Platon (Stephanus) immer der Werktitel angegeben werden?',
    options: [
      'Weil die drei Bände eigens paginiert sind',
      'Weil die Seitenzahl allein nicht eindeutig ist',
      'Weil Burnet es vorschreibt',
      'Weil es drei Bände gibt',
    ],
    correct: [0, 1],
    explain: 'Die Stephanus-Ausgabe ist dreibändig und jeder Band eigens paginiert → bloße Seitenzahl genügt nicht.',
  },
  {
    id: 'mc-cit-5', chapter: 'zitierweise',
    q: 'Was bezeichnet die Zeilenangabe bei einem Platon-Zitat?',
    options: ['Die Stephanus-Zeilen', 'Die Burnet-Oxford-Zeilen', 'Die Bekker-Zeilen', 'Die Diels-Kranz-Zeilen'],
    correct: [1],
    explain: 'Zeilenangaben folgen der wissenschaftlichen Standardausgabe von John Burnet (Oxford).',
  },
  {
    id: 'mc-cit-6', chapter: 'zitierweise',
    q: 'Nach welcher Ausgabe wird Aristoteles zitiert, und was bedeutet „a"?',
    options: [
      'Bekker-Ausgabe',
      '„a" = linke Spalte',
      '„a" = erstes Buch',
      'Stephanus-Ausgabe',
    ],
    correct: [0, 1],
    explain: 'Aristoteles → Bekker-Ausgabe. „a" = linke Spalte, „b" = rechte Spalte.',
  },
  {
    id: 'mc-cit-7', chapter: 'zitierweise',
    q: 'In „Phys. I 1 184a10": Was ist „184"?',
    options: ['Das Kapitel', 'Die Bekker-Seite', 'Die Zeile', 'Das Buch'],
    correct: [1],
    explain: '184 = Bekker-Seite, a = Spalte, 10 = Zeile; I = Buch, 1 = Kapitel.',
  },

  // ——— Grammatik ———
  {
    id: 'mc-gr-1', chapter: 'grammatik',
    q: 'Was besagt die grammatische Kategorie „Medium"?',
    options: [
      'Das Subjekt tut die Handlung für sich selbst (im eigenen Interesse)',
      'Das Subjekt ist zugleich das direkte Objekt',
      'Es hat oft reflexive Bedeutung',
      'Es bezeichnet immer eine Vergangenheit',
    ],
    correct: [0, 1, 2],
    explain: 'Medium = reflexiv / im eigenen Interesse; Subjekt ist zugleich Objekt. Es ist keine Zeitangabe.',
  },
  {
    id: 'mc-gr-2', chapter: 'grammatik',
    q: 'Welche sind die vier griechischen Verbalsysteme?',
    options: ['Präsens', 'Futur', 'Perfekt', 'Aorist'],
    correct: [0, 1, 2, 3],
    explain: 'Alle vier: Präsens, Futur, Perfekt, Aorist — unterschieden durch den Aspekt.',
  },
  {
    id: 'mc-gr-3', chapter: 'grammatik',
    q: 'Was kennzeichnet den Indikativ des Aorists stets?',
    options: ['Ein Augment (ἐ-)', 'Der Optativ', 'Ein Spiritus asper', 'Das Partikel ἂν'],
    correct: [0],
    explain: 'Der Indikativ Aorist trägt stets ein Augment (ἐ-) als Zeichen der Vergangenheit.',
  },
  {
    id: 'mc-gr-4', chapter: 'grammatik',
    q: 'Woher leitet sich „Aorist" ab?',
    options: [
      'Von ἀόριστος „unbegrenzt, unbestimmt"',
      'Aus ὅρος „Grenze" + α privativum',
      'Von ἀρχή „Anfang"',
      'Von einem lateinischen Wort',
    ],
    correct: [0, 1],
    explain: 'ἀόριστος = „unbegrenzt" — aus ὅρος „Grenze" und dem verneinenden α privativum.',
  },
  {
    id: 'mc-gr-5', chapter: 'grammatik',
    q: 'Welchen zusätzlichen Modus hat das Griechische gegenüber dem Deutschen?',
    options: ['Den Konjunktiv', 'Den Optativ', 'Den Imperativ', 'Den Indikativ'],
    correct: [1],
    explain: 'Zusätzlich der Optativ (Wunsch; mit ἂν → Potentialis).',
  },
  {
    id: 'mc-gr-6', chapter: 'grammatik',
    q: 'Was drückt der Optativ mit dem Partikel ἂν im Hauptsatz aus?',
    options: ['Einen Befehl', 'Einen Potentialis (Möglichkeitsform)', 'Eine Vergangenheit', 'Eine Frage'],
    correct: [1],
    explain: 'Optativ + ἂν ohne Wirklichkeitsbezug = Potentialis / Möglichkeitsform.',
  },
  {
    id: 'mc-gr-7', chapter: 'grammatik',
    q: 'Ordne richtig zu — was drücken die Stämme aus?',
    options: [
      'Präsensstamm → Andauerndes',
      'Aoriststamm → Vollzug',
      'Perfektstamm → Ergebnis',
      'Futurstamm → Vergangenheit',
    ],
    correct: [0, 1, 2],
    explain: 'Präsens = Andauerndes, Aorist = Vollzug, Perfekt = Ergebnis.',
  },
  {
    id: 'mc-gr-8', chapter: 'grammatik',
    q: 'Unterscheide εἶναι, ὄν und οὐσία:',
    options: [
      'εἶναι = Infinitiv „(zu) sein"',
      'ὄν = Partizip „seiend / das Seiende"',
      'οὐσία = Substantiv „Seiendheit, Wesen"',
      'οὐσία = Infinitiv',
    ],
    correct: [0, 1, 2],
    explain: 'εἶναι (Inf.), ὄν (Partizip), οὐσία (Substantiv „Seiendheit, Wesen").',
  },
  {
    id: 'mc-gr-9', chapter: 'grammatik',
    q: 'Was ist ein ACI (Accusativus cum Infinitivo)?',
    options: [
      'Eine Konstruktion aus Akkusativ + Infinitiv',
      'Im Deutschen oft mit „dass" übersetzt',
      'Der Akkusativ wird zum Subjekt, der Infinitiv zum Prädikat',
      'Eine Form des Optativs',
    ],
    correct: [0, 1, 2],
    explain: 'ACI: Akk. + Inf. → „dass"-Satz; Akk. wird Subjekt, Inf. wird Prädikat.',
  },

  // ——— Weitere Zitierweisen aus den Handouts ———
  {
    id: 'mc-cit-8', chapter: 'zitierweise',
    q: 'Welche Angaben gehören zu „La. 179 c1"?',
    options: ['La. = Laches', '179 = Stephanus-Seite', 'c = Stephanus-Abschnitt', '1 = Bekker-Zeile'],
    correct: [0, 1, 2],
    explain: 'La. 179 c1 ist ein Platon-Zitat: Werk Laches, Stephanus-Seite 179, Abschnitt c, Burnet-Zeile 1. Bekker gehört zu Aristoteles.',
  },
  {
    id: 'mc-cit-9', chapter: 'zitierweise',
    q: 'Welche Aussagen zur Bekker-Ausgabe sind richtig?',
    options: [
      'Sie ist die Standardzählung für Aristoteles.',
      'Die Seitenzahlen sind nicht mehrfach vergeben.',
      'a und b bezeichnen linke und rechte Spalte.',
      'Der Werktitel ist wegen dreier eigens paginierter Bände immer zwingend.',
    ],
    correct: [0, 1, 2],
    explain: 'Aristoteles wird nach Bekker zitiert: Seite, Spalte a/b, Zeile. Die Pflicht zum Werktitel wegen eigens paginierter Bände betrifft Platon/Stephanus.',
  },
  {
    id: 'mc-cit-10', chapter: 'zitierweise',
    q: 'In „Arist. Phys. A 1 184a10": Was bedeutet „A 1"?',
    options: ['1. Buch und 1. Kapitel', 'Autor und Werk', 'Seite und Spalte', 'Fragment und Testimonium'],
    correct: [0],
    explain: 'A steht hier für das 1. Buch, 1 für das 1. Kapitel. 184a10 ist die Bekker-Stelle.',
  },

  // ——— Vokabular ———
  {
    id: 'mc-voc-1', chapter: 'vokabular',
    q: 'Welche Übersetzungen frühgriechischer Termini passen?',
    options: ['νοεῖν = denken', 'δίκη = Recht', 'ἀρχή = Anfang / Urgrund', 'μοῖρα = Werkzeug'],
    correct: [0, 1, 2],
    explain: 'νοεῖν heißt denken, δίκη Recht, ἀρχή Anfang/Urgrund. μοῖρα bedeutet Anteil, Los oder Schicksal.',
  },
  {
    id: 'mc-voc-2', chapter: 'vokabular',
    q: 'Welche Begriffe gehören besonders in den vorsokratischen Stoff?',
    options: ['ἄπειρον', 'χρεών', 'λόγος', 'προαίρεσις'],
    correct: [0, 1, 2],
    explain: 'ἄπειρον, χρεών und λόγος begegnen im vorsokratischen Stoff. προαίρεσις ist ein aristotelischer Ausdruck.',
  },
  {
    id: 'mc-voc-3', chapter: 'vokabular',
    q: 'Welche Übersetzungen platonischer Begriffe sind richtig?',
    options: ['μέθεξις = Teilhabe', 'εἶδος = Gestalt / Form / Idee', 'ἐπιστήμη = Wissen', 'ὄργανον = Lust'],
    correct: [0, 1, 2],
    explain: 'μέθεξις = Teilhabe, εἶδος = Gestalt/Form/Idee, ἐπιστήμη = Wissen/Können. ὄργανον heißt Werkzeug.',
  },
  {
    id: 'mc-voc-4', chapter: 'vokabular',
    q: 'Welche Begriffe sind typisch aristotelisch in der Prüfungsliste?',
    options: ['κατηγορία', 'ἐντελέχεια', 'ὑποκείμενον', 'ὕμνος'],
    correct: [0, 1, 2],
    explain: 'κατηγορία, ἐντελέχεια und ὑποκείμενον stehen in der aristotelischen Liste. ὕμνος ist ein Transkriptions-/Allgemeinwort.',
  },
  {
    id: 'mc-voc-5', chapter: 'vokabular',
    q: 'Was kann οὐσία bedeuten?',
    options: ['Seiendheit', 'Wesen', 'Substanz', 'Fragezeichen'],
    correct: [0, 1, 2],
    explain: 'οὐσία bezeichnet Seiendheit, Wesen oder Substanz. Das Fragezeichen gehört zur Interpunktion.',
  },
  {
    id: 'mc-voc-6', chapter: 'vokabular',
    q: 'Welche Zuordnungen sind falsch?',
    options: ['τέλος = Ziel / Zweck', 'ὕλη = Materie', 'ἡδονή = Lust', 'σύμβολον = Bewegung'],
    correct: [3],
    explain: 'σύμβολον bedeutet Erkennungszeichen. Bewegung ist κίνησις.',
  },
  {
    id: 'mc-voc-7', chapter: 'vokabular',
    q: 'Welche Wörter trainieren ausdrücklich Spiritus-asper-Regeln?',
    options: ['ἁμαρτία → hamartía', 'Ἑλλάς → Hellás', 'υἱός → hyiós', 'ἀρχή → harchḗ'],
    correct: [0, 1, 2],
    explain: 'ἁμαρτία, Ἑλλάς und υἱός zeigen Behauchung mit h. ἀρχή hat Spiritus lenis und wird archḗ transkribiert.',
  },
  {
    id: 'mc-voc-8', chapter: 'vokabular',
    q: 'Welche Übersetzungen aus den Xenophanes-/Heraklit-Vokabeln passen?',
    options: ['ψόγος = Tadel / Schimpf', 'κλέπτειν = stehlen', 'μοιχεύειν = ehebrechen', 'ἀπατεύειν = denken'],
    correct: [0, 1, 2],
    explain: 'ψόγος = Tadel/Schimpf, κλέπτειν = stehlen, μοιχεύειν = ehebrechen. ἀπατεύειν heißt betrügen/täuschen.',
  },
  {
    id: 'mc-voc-9', chapter: 'vokabular',
    q: 'Welche Wörter gehören zur Wortfamilie von Denken/Sein aus Frage 9?',
    options: ['νοεῖν', 'νόησις', 'νόημα', 'νοούμενα'],
    correct: [0, 1, 2, 3],
    explain: 'Die Handouts verbinden νοεῖν mit νόησις (Tätigkeit), νόημα (Ergebnis) und νοούμενα (Inhalt/das Gedachte).',
  },
  {
    id: 'mc-voc-10', chapter: 'vokabular',
    q: 'Welche Begriffe sind für Anaximanders Fragment wichtig?',
    options: ['ἄπειρον = das Unendliche', 'χρεών = Notwendigkeit', 'τίσις = Buße / Strafe', 'τάξις = Ordnung'],
    correct: [0, 1, 2, 3],
    explain: 'Alle vier stehen im Umfeld von DK 12 B 1: Ursprung, Notwendigkeit, Recht/Buße und Ordnung der Zeit.',
  },
  {
    id: 'mc-voc-11', chapter: 'vokabular',
    q: 'Welche Übersetzungen der Musterfragen-Liste stimmen?',
    options: ['κατηγορία = Anklage / Aussage', 'προαίρεσις = Entscheidung / Vorsatz', 'ἕξις = Haltung / Zustand', 'μεταβολή = Name'],
    correct: [0, 1, 2],
    explain: 'μεταβολή heißt Umschlag/Veränderung. Name ist ὄνομα.',
  },
  {
    id: 'mc-voc-12', chapter: 'vokabular',
    q: 'Welche Transkriptionswörter aus dem Muster sind korrekt übersetzt?',
    options: ['σῦριγξ = Panflöte', 'ὀρχήστρα = Tanzplatz im Theater', 'ζάγκλον = Sichel', 'δεκάπηχυς = zehn Ellen lang'],
    correct: [0, 1, 2, 3],
    explain: 'Diese vier kommen in den Transkriptionsübungen bzw. Musterfragen vor und sind so im Vokabular hinterlegt.',
  },

  // ——— Zusätzliche Grammatik aus Folien/Formenlehre ———
  {
    id: 'mc-gr-10', chapter: 'grammatik',
    q: 'Welche Angaben zur Formenlehre von εἰμί sind richtig?',
    options: ['εἰμί = ich bin', 'εἶ = du bist', 'ἐστί(ν) = er/sie/es ist', 'εἶναι = Infinitiv sein'],
    correct: [0, 1, 2, 3],
    explain: 'Alle vier Formen stehen im Formenlehre-Handout zu εἰμί.',
  },
  {
    id: 'mc-gr-11', chapter: 'grammatik',
    q: 'Was kennzeichnet γίγνομαι in der Formenlehre?',
    options: ['Es ist Medium/Passiv in der Form.', 'Es wird als Deponens behandelt.', 'Es bedeutet werden.', 'Es ist ein normales Aktivverb mit -ω-Endungen.'],
    correct: [0, 1, 2],
    explain: 'γίγνομαι wird als Medium/Passiv-Form und Deponens gelernt; Bedeutung: werden.',
  },
  {
    id: 'mc-gr-12', chapter: 'grammatik',
    q: 'Welche Spezialfälle der Kasus werden im Stoff genannt?',
    options: ['dativus possessoris', 'accusativus respectus', 'genitivus objectivus/subjectivus', 'ablativus absolutus'],
    correct: [0, 1, 2],
    explain: 'Genannt werden dativus possessoris, accusativus respectus und genitivus objectivus/subjectivus. Einen Ablativ gibt es im Griechisch-Stoff hier nicht.',
  },
  {
    id: 'mc-gr-13', chapter: 'grammatik',
    q: 'Wie wird der gnomische Aorist übersetzt?',
    options: [
      'Als allgemeingültige Aussage oder Erfahrungstatsache',
      'Nicht zwingend mit deutscher Vergangenheit',
      'Immer als Befehl',
      'Nur als Futur',
    ],
    correct: [0, 1],
    explain: 'Der gnomische Aorist kann Allgemeingültiges ausdrücken und wird dann nicht einfach als Vergangenheit übersetzt.',
  },
  {
    id: 'mc-gr-14', chapter: 'grammatik',
    q: 'Welche Schritte gehören zur Übersetzungsmethode aus den Folien?',
    options: ['verbales Prädikat suchen', 'Subjekt im Nominativ suchen', 'Objekte/Attribute bestimmen', 'zuerst jedes Wort alphabetisch sortieren'],
    correct: [0, 1, 2],
    explain: 'Die Methode: Prädikat, Subjekt, dann Prädikativum/Objekte/Attribute und Valenzformel. Alphabetisches Sortieren gehört nicht dazu.',
  },

  // ——— Fragmente ———
  {
    id: 'mc-fr-1', chapter: 'fragmente',
    q: 'Welches Fragment lautet sinngemäß „Denn dasselbe ist Denken und Sein"?',
    options: ['D-K 28 B 3 (Parmenides)', 'DK 22 B 53 (Heraklit)', 'DK 12 B 1 (Anaximander)', 'Phaidon 100c'],
    correct: [0],
    explain: 'D-K 28 B 3 von Parmenides: τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι.',
  },
  {
    id: 'mc-fr-2', chapter: 'fragmente',
    q: 'Welche Heraklit-Fragmente sind im Builder enthalten?',
    options: ['DK 22 B 1', 'DK 22 B 45', 'DK 22 B 53', 'DK 22 B 49a'],
    correct: [0, 1, 2, 3],
    explain: 'Alle vier Heraklit-Stellen sind in den Folien und im Fragment-Builder enthalten.',
  },
  {
    id: 'mc-fr-3', chapter: 'fragmente',
    q: 'Welche Übersetzung gehört zu Heraklit DK 22 B 53?',
    options: [
      'Krieg ist aller Dinge Vater und König.',
      'Ein Gott ist unter Göttern und Menschen der größte.',
      'Der Ursprung des Seienden sei das Unendliche.',
      'Was ist das immer Seiende?',
    ],
    correct: [0],
    explain: 'DK 22 B 53 ist das polemos-Fragment: Krieg ist Vater/König aller Dinge.',
  },
  {
    id: 'mc-fr-4', chapter: 'fragmente',
    q: 'Welche Aussagen zu Xenophanes DK 21 B 11 stimmen?',
    options: [
      'Homer und Hesiod hängen den Göttern menschliche Schandtaten an.',
      'κλέπτειν, μοιχεύειν und ἀπατεύειν werden genannt.',
      'Es gehört zur Xenophanes-Einheit.',
      'Es ist ein Aristoteles-Bekker-Zitat.',
    ],
    correct: [0, 1, 2],
    explain: 'DK 21 B 11 ist ein Vorsokratiker-Fragment bei Xenophanes, kein Bekker-Zitat.',
  },
  {
    id: 'mc-fr-5', chapter: 'fragmente',
    q: 'Welches Fragment enthält ἄπειρον, χρεών, δίκη/τίσις und τάξις χρόνου?',
    options: ['DK 12 B 1 (Anaximander)', 'DK 21 B 23 (Xenophanes)', 'DK 22 B 45 (Heraklit)', 'Phaidon 99e'],
    correct: [0],
    explain: 'Anaximander DK 12 B 1 verbindet das Unendliche, Notwendigkeit, Recht/Buße und die Ordnung der Zeit.',
  },
  {
    id: 'mc-fr-6', chapter: 'fragmente',
    q: 'Welche Platon-Stellen aus dem Stoff gehören zum Phaidon?',
    options: ['Phaidon 99e', 'Phaidon 100b', 'Phaidon 100c', 'Timaios 27d–28a'],
    correct: [0, 1, 2],
    explain: 'Phaidon 99e, 100b und 100c sind Phaidon-Stellen. Timaios 27d–28a gehört zum Timaios.',
  },
  {
    id: 'mc-fr-7', chapter: 'fragmente',
    q: 'Welche Stelle fragt nach dem „immer Seienden" und dem „immer Werdenden"?',
    options: ['Platon, Timaios 27d–28a', 'Platon, Phaidon 99e', 'DK 28 B 3', 'DK 21 B 11'],
    correct: [0],
    explain: 'Timaios 27d–28a unterscheidet das immer Seiende ohne Werden vom immer Werdenden, das niemals seiend ist.',
  },
  {
    id: 'mc-fr-8', chapter: 'fragmente',
    q: 'Welche Fragmente werden im Stoff Xenophanes zugeschrieben?',
    options: ['DK 21 B 23', 'DK 21 B 11', 'DK 22 B 1', 'DK 12 B 1'],
    correct: [0, 1],
    explain: 'Xenophanes: DK 21 B 23 und DK 21 B 11. DK 22 ist Heraklit; DK 12 ist Anaximander.',
  },
  {
    id: 'mc-fr-9', chapter: 'fragmente',
    q: 'Welche Aussage passt zu Platon, Phaidon 100c?',
    options: [
      'Etwas ist schön, weil es am Schönen selbst Anteil hat.',
      'Krieg macht die einen zu Sklaven, die anderen zu Freien.',
      'Der Ursprung des Seienden sei Wasser.',
      'Das griechische Semikolon ist ein Fragezeichen.',
    ],
    correct: [0],
    explain: 'Phaidon 100c erklärt Schönheit durch Teilhabe am Schönen selbst.',
  },
  {
    id: 'mc-fr-10', chapter: 'fragmente',
    q: 'Welche Wortgruppen gehören zur Übersetzung von Heraklit DK 22 B 45?',
    options: ['Grenzen des Lebensodems', 'nicht ausfindig machen', 'jeden Weg durchwandern', 'Tanzplatz im Theater'],
    correct: [0, 1, 2],
    explain: 'DK 22 B 45 behandelt die Grenzen der ψυχή und den tiefen Logos. Tanzplatz im Theater ist ὀρχήστρα.',
  },
]
