import type { TypeItem } from './types'

// Greek ↔ transcription pairs used in the typing trainer.
// Includes every word from the Muster-Prüfung Q1 / Q1a plus folien exercises.
export interface TransWord {
  gr: string
  tr: string
  de?: string
}

export const TRANS_WORDS: TransWord[] = [
  // Muster Q1 (griech → lat)
  { gr: 'ποιητική', tr: 'poiētikḗ', de: 'Dichtkunst' },
  { gr: 'ὥσπερ', tr: 'hṓsper', de: 'wie' },
  { gr: 'μῦθος', tr: 'mŷthos', de: 'Erzählung' },
  { gr: 'αὐλητική', tr: 'aulētikḗ', de: 'Flötenspielkunst' },
  { gr: 'σῦριγξ', tr: 'sûrinx', de: 'Panflöte' },
  { gr: 'διθύραμβος', tr: 'dithýrambos', de: 'Dithyrambus' },
  { gr: 'κνίζω', tr: 'knízō', de: 'kratzen, reizen' },
  { gr: 'ῥίνη', tr: 'rhínē', de: 'Feile' },
  { gr: 'ψυχή', tr: 'psychḗ', de: 'Seele' },
  { gr: 'φύσις', tr: 'phýsis', de: 'Natur' },
  // Muster Q1a (lat → griech)
  { gr: 'ὕμνος', tr: 'hýmnos', de: 'Hymne' },
  { gr: 'ψόγος', tr: 'psógos', de: 'Tadel, Schimpf' },
  { gr: 'αἴτιον', tr: 'aítion', de: 'Ursache' },
  { gr: 'τραγῳδία', tr: 'tragōdía', de: 'Tragödie' },
  { gr: 'ξουθός', tr: 'xuthós', de: 'goldgelb / flink' },
  { gr: 'μεταβαλεῖν', tr: 'metabaleîn', de: 'umwenden' },
  { gr: 'ὀρχήστρα', tr: 'orchḗstra', de: 'Tanzplatz im Theater' },
  { gr: 'βαίνω', tr: 'baínō', de: 'gehen' },
  { gr: 'ζάγκλον', tr: 'zánklon', de: 'Sichel' },
  { gr: 'δεκάπηχυς', tr: 'dekápēchys', de: 'zehn Ellen lang' },
  // Folien exercises (Einheit 1–10)
  { gr: 'σοφία', tr: 'sophía', de: 'Weisheit' },
  { gr: 'τέλος', tr: 'télos', de: 'Ziel, Zweck' },
  { gr: 'ἐπιστήμη', tr: 'epistḗmē', de: 'Wissen, Können' },
  { gr: 'δόξα', tr: 'dóxa', de: 'Meinung, Schein' },
  { gr: 'διαφωνία', tr: 'diaphōnía', de: 'Dissonanz' },
  { gr: 'κόσμος', tr: 'kósmos', de: 'Ordnung, Universum' },
  { gr: 'παράδειγμα', tr: 'parádeigma', de: 'Beispiel, Muster' },
  { gr: 'ζῷον', tr: 'zôon', de: 'Lebewesen, Tier' },
  { gr: 'δημιουργός', tr: 'dēmiourgós', de: 'Handwerker, Demiurg' },
  { gr: 'συνώνυμος', tr: 'synṓnymos', de: 'gleichnamig' },
  { gr: 'αἰτία', tr: 'aitía', de: 'Grund, Ursache' },
  { gr: 'ὑποκείμενον', tr: 'hypokeímenon', de: 'das Zugrundeliegende' },
  { gr: 'νόησις', tr: 'nóēsis', de: 'Denken' },
  { gr: 'διάνοια', tr: 'diánoia', de: 'Denkvermögen, Verstand' },
  { gr: 'ἀγαθός', tr: 'agathós', de: 'gut' },
  { gr: 'τέχνη', tr: 'téchnē', de: 'Kunstfertigkeit' },
  { gr: 'ῥήτωρ', tr: 'rhḗtōr', de: 'Redner' },
  { gr: 'ὕδωρ', tr: 'hýdōr', de: 'Wasser' },
  { gr: 'ἀρετή', tr: 'aretḗ', de: 'Tugend' },
  { gr: 'ἐλπίς', tr: 'elpís', de: 'Hoffnung' },
  { gr: 'ἀνάγκη', tr: 'anánkē', de: 'Notwendigkeit' },
  { gr: 'δικαιοσύνη', tr: 'dikaiosýnē', de: 'Gerechtigkeit' },
  { gr: 'ῥιζώματα', tr: 'rhizṓmata', de: 'Verwurzelungen' },
  { gr: 'σφαῖρα', tr: 'sphaîra', de: 'Kugel' },
  { gr: 'σύμβολον', tr: 'sýmbolon', de: 'Erkennungszeichen' },
  { gr: 'φθορά', tr: 'phthorá', de: 'Vergehen' },
  { gr: 'ἄνθρωπος', tr: 'ánthrōpos', de: 'Mensch' },
  { gr: 'διδάσκω', tr: 'didáskō', de: 'lehren' },
  { gr: 'εἶδος', tr: 'eîdos', de: 'Gestalt, Idee' },
  { gr: 'ῥυθμός', tr: 'rhythmós', de: 'Rhythmus' },
  { gr: 'πόλεμος', tr: 'pólemos', de: 'Krieg' },
  { gr: 'ἱστορία', tr: 'historía', de: 'Forschung' },
  { gr: 'κατηγορία', tr: 'katēgoría', de: 'Anklage, Aussage' },
  { gr: 'πάθημα', tr: 'páthēma', de: 'Erlebnis' },
  { gr: 'πρᾶγμα', tr: 'prâgma', de: 'Handlung, Sache' },
  { gr: 'οὐσία', tr: 'ousía', de: 'Seiendheit, Wesen' },
  { gr: 'ποιότης', tr: 'poiótēs', de: 'Qualität' },
  { gr: 'ὄνομα', tr: 'ónoma', de: 'Name' },
  { gr: 'χρεών', tr: 'chreṓn', de: 'Notwendigkeit' },
  { gr: 'πατήρ', tr: 'patḗr', de: 'Vater' },
  { gr: 'δίκη', tr: 'díkē', de: 'Recht' },
  { gr: 'ἄπειρον', tr: 'ápeiron', de: 'das Unendliche' },
  { gr: 'μέγας', tr: 'mégas', de: 'groß' },
  { gr: 'δέμας', tr: 'démas', de: 'Gestalt' },
  { gr: 'θνητός', tr: 'thnētós', de: 'sterblich' },
  { gr: 'μοῖρα', tr: 'moîra', de: 'Anteil, Schicksal' },
  { gr: 'μέθεξις', tr: 'méthexis', de: 'Teilhabe' },
  { gr: 'ὕλη', tr: 'hýlē', de: 'Materie' },
  { gr: 'αἴσθησις', tr: 'aísthēsis', de: 'Wahrnehmung' },
  { gr: 'ἀλήθεια', tr: 'alḗtheia', de: 'Wahrheit' },
  { gr: 'παιδιά', tr: 'paidiá', de: 'Spiel' },
  { gr: 'φαίνομαι', tr: 'phaínomai', de: 'erscheinen' },
  { gr: 'κοῦρος', tr: 'koûros', de: 'Jüngling' },
  { gr: 'ὕβρις', tr: 'hýbris', de: 'Übermaß, Hochmut' },
  { gr: 'διαίρεσις', tr: 'diaíresis', de: 'Begriffsbestimmung' },
  { gr: 'κατάληψις', tr: 'katálēpsis', de: 'Erfassung' },
  { gr: 'σύγγραμμα', tr: 'sýngramma', de: 'Schrift, Abhandlung' },
  { gr: 'ἵππος', tr: 'híppos', de: 'Pferd' },
  { gr: 'φιλόσοφος', tr: 'philósophos', de: 'Philosoph' },
  { gr: 'λανθάνω', tr: 'lanthánō', de: 'verborgen bleiben' },
  { gr: 'ἐντελέχεια', tr: 'entelécheia', de: '(vollendete) Wirklichkeit' },
  { gr: 'ἐγκράτεια', tr: 'enkráteia', de: 'Selbstbeherrschung' },
  { gr: 'τυγχάνω', tr: 'tynchánō', de: 'treffen' },
  { gr: 'στάσις', tr: 'stásis', de: 'Stand, Bürgerkrieg' },
  // Handout examples and Muster words that exercise the special transcription rules.
  { gr: 'ἁμαρτία', tr: 'hamartía', de: 'Fehler, Verfehlung' },
  { gr: 'Ἑλλάς', tr: 'Hellás', de: 'Griechenland' },
  { gr: 'αἵρεσις', tr: 'haíresis', de: 'Wahl, Richtung, Schule' },
  { gr: 'εὐδαιμονία', tr: 'eudaimonía', de: 'Glückseligkeit' },
  { gr: 'ἀγγέλλω', tr: 'angélō', de: 'melden, verkünden' },
  { gr: 'ὄν', tr: 'ón', de: 'seiend, das Seiende' },
  { gr: 'νόημα', tr: 'nóēma', de: 'Gedanke' },
  { gr: 'νοούμενα', tr: 'noúmena', de: 'das Gedachte' },
  { gr: 'πεῖραρ', tr: 'peîrar', de: 'Grenze' },
  { gr: 'τίσις', tr: 'tísis', de: 'Buße, Strafe' },
  { gr: 'τάξις', tr: 'táxis', de: 'Ordnung' },
  { gr: 'ἀδικία', tr: 'adikía', de: 'Unrecht' },
  { gr: 'ἄλλος', tr: 'állos', de: 'anderer' },
  { gr: 'καλός', tr: 'kalós', de: 'schön, gut' },
  { gr: 'κατὰ ταὐτά', tr: 'katà tautá', de: 'gemäß demselben' },
  { gr: 'προσποίησις', tr: 'prospoíēsis', de: 'Verstärkung, Anspruch, Anmaßung' },
  { gr: 'συγκεφαλαιόω', tr: 'synkephalaióō', de: 'zusammenfassen' },
  { gr: 'ὑπερβολή', tr: 'hyperbolḗ', de: 'Übersteigung' },
  { gr: 'ὑπερβάλλω', tr: 'hyper-bállō', de: 'übertreffen' },
  { gr: 'ἀξύνετος', tr: 'axýnetos', de: 'unverständlich' },
  { gr: 'ἀεί', tr: 'aeí', de: 'immer' },
  { gr: 'ἐξευρίσκω', tr: 'exeurískō', de: 'ausfindig machen' },
  { gr: 'ὁδός', tr: 'hodós', de: 'Weg' },
  { gr: 'βαθύς', tr: 'bathýs', de: 'tief' },
  { gr: 'οὕτω', tr: 'hoútō', de: 'so' },
  { gr: 'ἔχω', tr: 'échō', de: 'haben, halten' },
  { gr: 'πᾶς', tr: 'pâs', de: 'jeder, ganz' },
  { gr: 'λύω', tr: 'lýō', de: 'lösen, befreien' },
  { gr: 'λύομαι', tr: 'lýomai', de: 'ich befreie mich' },
  { gr: 'αἰχμάλωτος', tr: 'aichmálōtos', de: 'Gefangener' },
  { gr: 'παιδεύω', tr: 'paideúō', de: 'erziehen, unterrichten' },
  { gr: 'παῖς', tr: 'paîs', de: 'Kind' },
  { gr: 'διδάσκαλος', tr: 'didáskalos', de: 'Lehrer' },
  { gr: 'βασιλεύς', tr: 'basileús', de: 'König' },
  { gr: 'δείκνυμι', tr: 'deíknymi', de: 'zeigen' },
  { gr: 'ἔδειξε', tr: 'édeixe', de: 'er zeigte' },
  { gr: 'ποιέω', tr: 'poiéō', de: 'machen' },
  { gr: 'ἐποίησε', tr: 'epoíēse', de: 'er machte' },
  { gr: 'δοῦλος', tr: 'doûlos', de: 'Sklave' },
  { gr: 'ἐλεύθερος', tr: 'eleútheros', de: 'frei' },
  { gr: 'μέν', tr: 'mén', de: 'zwar, einerseits' },
  { gr: 'δέ', tr: 'dé', de: 'aber, andererseits' },
  { gr: 'ἐπιεικεύω', tr: 'epieikeúō', de: 'nachsichtig sein' },
  { gr: 'ἀναγκαστός', tr: 'anankastós', de: 'erzwungen' },
  { gr: 'ἀγκύλη', tr: 'ankýlē', de: 'Krümmung' },
  { gr: 'ἐμβαίνω', tr: 'embaínō', de: 'hineinsteigen' },
  { gr: 'ποταμός', tr: 'potamós', de: 'Fluss' },
  { gr: 'αὐτός', tr: 'autós', de: 'selbst, derselbe' },
  { gr: 'οὐκ', tr: 'ouk', de: 'nicht' },
  { gr: 'εἶμεν', tr: 'eîmen', de: 'wir sind' },
  { gr: 'εἷς', tr: 'heîs', de: 'ein' },
  { gr: 'ἔν', tr: 'én', de: 'unter' },
  { gr: 'μέγιστος', tr: 'mégistos', de: 'größter' },
  { gr: 'οὔτι', tr: 'oúti', de: 'gar nicht' },
  { gr: 'ὅμοιος', tr: 'hómoios', de: 'ähnlich' },
  { gr: 'οὐδέ', tr: 'oudé', de: 'und nicht, noch' },
  { gr: 'εἴρηκε', tr: 'eírēke', de: 'er hat gesagt' },
  { gr: 'ταῦτα', tr: 'taûta', de: 'diese Dinge' },
  { gr: 'δίδωμι', tr: 'dídōmi', de: 'geben' },
  { gr: 'ἀλλήλων', tr: 'allḗlōn', de: 'einander' },
  { gr: 'ἰατρόμαντις', tr: 'iatrómantis', de: 'Heiler' },
  { gr: 'ἔγχος', tr: 'énchos', de: 'Speer' },
  { gr: 'Ὅμηρος', tr: 'Hómēros', de: 'Homer' },
  { gr: 'Ἡσίοδος', tr: 'Hēsíodos', de: 'Hesiod' },
  { gr: 'ὅσσα', tr: 'hóssa', de: 'so viel wie' },
  { gr: 'παρά', tr: 'pará', de: 'bei, neben' },
  { gr: 'ὀνείδεα', tr: 'oneídea', de: 'Tadel' },
  { gr: 'πάντα', tr: 'pánta', de: 'alles' },
  { gr: 'ἐπικαγχαλάω', tr: 'epikanchaláō', de: 'darauf stolz sein' },
  { gr: 'προσχράομαι', tr: 'proschráomai', de: 'zu Hilfe nehmen' },
  { gr: 'λυπηρός', tr: 'lypērós', de: 'betrübend' },
  { gr: 'πρεσβεία', tr: 'presbeía', de: 'Würde des Älteren' },
  { gr: 'θάτερον', tr: 'tháteron', de: 'das Verschiedene' },
  { gr: 'Φερεκύδης', tr: 'Pherekýdēs', de: 'Pherekydes' },
  { gr: 'Ἑλλάνικος', tr: 'Hellánikos', de: 'Hellanikos' },
  { gr: 'Δαΐμαχος', tr: 'Daímachos', de: 'Daimachos' },
  { gr: 'Φίλων', tr: 'Phílōn', de: 'Philon' },
  { gr: 'Σόλων', tr: 'Sólōn', de: 'Solon' },
  { gr: 'Ἐπιμενίδης', tr: 'Epimenídēs', de: 'Epimenides' },
  { gr: 'Κλεόβουλος', tr: 'Kleóboulos', de: 'Kleoboulos' },
  { gr: 'Ἀναξαγόρας', tr: 'Anaxagóras', de: 'Anaxagoras' },
  { gr: 'Πεισίστρατος', tr: 'Peisístratos', de: 'Peisistratos' },
  { gr: 'ἔδοξε', tr: 'édoxe', de: 'es schien' },
  { gr: 'δοκέω', tr: 'dokéō', de: 'meinen, scheinen' },
  { gr: 'μοι', tr: 'moi', de: 'mir' },
  { gr: 'χρῆναι', tr: 'chrênai', de: 'notwendig sein' },
  { gr: 'χρή', tr: 'chrḗ', de: 'es ist nötig' },
  { gr: 'καταφεύγω', tr: 'katapheúgō', de: 'hinfliehen' },
  { gr: 'σκοπέω', tr: 'skopéō', de: 'untersuchen' },
  { gr: 'ἐκείνοις', tr: 'ekeínois', de: 'in ihnen' },
  { gr: 'προπιδεῖον', tr: 'propideîon', de: 'nachbessern' },
  { gr: 'γραμματοδιδασκαλεῖον', tr: 'grammatodidaskaleîon', de: 'Grundschule' },
  { gr: 'ἐπικράτεια', tr: 'epikráteia', de: 'Oberherrschaft' },
  { gr: 'ὀψαρτυτής', tr: 'opsartytḗs', de: 'Speisenzubereiter' },
  { gr: 'ἰχθυόεις', tr: 'ichthyóeis', de: 'fischig, fischreich' },
  { gr: 'ἐπιχειρέω', tr: 'epicheiréō', de: 'versuchen' },
  { gr: 'κυουμένη', tr: 'kyouménē', de: 'schwanger, seiend' },
  { gr: 'ἀγκών', tr: 'ankṓn', de: 'Ellenbogen' },
  { gr: 'σχολαστικός', tr: 'scholastikós', de: 'müßig' },
  { gr: 'ταχύπνοια', tr: 'tachýpnoia', de: 'schnelles Atemholen' },
  { gr: 'ἔρχομαι', tr: 'érchomai', de: 'gehen, kommen' },
  { gr: 'ἐπιδείκνυμι', tr: 'epideíknymi', de: 'zeigen, vorführen' },
  { gr: 'πάλιν', tr: 'pálin', de: 'wieder' },
  { gr: 'ὑποθέμενος', tr: 'hypothémenos', de: 'voraussetzend' },
  { gr: "καθ' αὑτό", tr: "kath' hautó", de: 'gemäß sich selbst' },
  { gr: 'πλήν', tr: 'plḗn', de: 'außer' },
  { gr: 'διά', tr: 'diá', de: 'durch, wegen' },
  { gr: 'ἕν', tr: 'hén', de: 'eins' },
  { gr: 'διότι', tr: 'dióti', de: 'weil' },
  { gr: 'μετέχω', tr: 'metéchō', de: 'Anteil haben' },
  { gr: 'ἐκεῖνος', tr: 'ekeînos', de: 'jener' },
  { gr: 'χωρέω', tr: 'chōréō', de: 'weichen, gehen' },
]

// Build typing items (both directions) from the bank.
export function buildTypeItems(): TypeItem[] {
  const items: TypeItem[] = []
  for (const w of TRANS_WORDS) {
    items.push({
      id: `t-g2l-${w.tr}`,
      prompt: w.gr,
      answer: w.tr,
      direction: 'gr2lat',
      hint: w.de,
    })
    items.push({
      id: `t-l2g-${w.tr}`,
      prompt: w.tr,
      answer: w.gr,
      direction: 'lat2gr',
      hint: w.de,
    })
  }
  return items
}
