import type { Vocab } from './types'

// Complete philosophical vocabulary from the course (Einheit 1–10 + Muster).
// group reflects the exam grouping where the term is explicitly listed:
//   vorsokratiker = Frage 3 / frühgriechisch · platon = Frage 5 · aristoteles = Frage 7
//   allgemein = general terminology & transcription vocabulary.

export const VOCAB: Vocab[] = [
  // ——— Frühgriechisch / Vorsokratiker (Frage 3) ———
  { id: 'noein', gr: 'νοεῖν', tr: 'noeîn', de: 'denken', group: 'vorsokratiker', note: 'Inf. zu νοέω' },
  { id: 'dike', gr: 'δίκη', tr: 'díkē', de: 'Recht', group: 'vorsokratiker' },
  { id: 'arche', gr: 'ἀρχή', tr: 'archḗ', de: 'Anfang, Urgrund', group: 'vorsokratiker' },
  { id: 'moira', gr: 'μοῖρα', tr: 'moîra', de: 'Teil, Anteil, Los, Schicksal', group: 'vorsokratiker' },
  { id: 'theos', gr: 'θεός', tr: 'theós', de: 'Gott', group: 'vorsokratiker' },
  { id: 'rhema', gr: 'ῥῆμα', tr: 'rhêma', de: 'Wort, Verbum', group: 'vorsokratiker' },
  { id: 'hydor', gr: 'ὕδωρ', tr: 'hýdōr', de: 'Wasser', group: 'vorsokratiker' },
  { id: 'phora', gr: 'φορά', tr: 'phorá', de: 'Bewegung, das (Sich-)Tragen', group: 'vorsokratiker' },
  { id: 'phthora', gr: 'φθορά', tr: 'phthorá', de: 'Zerstörung, Vergehen', group: 'vorsokratiker' },
  { id: 'apeiron', gr: 'ἄπειρον', tr: 'ápeiron', de: 'das Unendliche', group: 'vorsokratiker' },
  { id: 'chreon', gr: 'χρεών', tr: 'chreṓn', de: 'Notwendigkeit, Schicksal', group: 'vorsokratiker' },
  { id: 'logos', gr: 'λόγος', tr: 'lógos', de: 'Rede, Wort, Argument, Vernunft', group: 'vorsokratiker', note: 'vieldeutiger Begriff' },
  { id: 'kosmos', gr: 'κόσμος', tr: 'kósmos', de: 'Ordnung, Schmuck, Universum', group: 'vorsokratiker' },
  { id: 'arete', gr: 'ἀρετή', tr: 'aretḗ', de: 'Vortrefflichkeit, Bestform, Tugend', group: 'vorsokratiker' },
  { id: 'elpis', gr: 'ἐλπίς', tr: 'elpís', de: 'Hoffnung', group: 'vorsokratiker' },
  { id: 'ananke', gr: 'ἀνάγκη', tr: 'anánkē', de: 'Zwang, Notwendigkeit', group: 'vorsokratiker' },
  { id: 'dikaiosyne', gr: 'δικαιοσύνη', tr: 'dikaiosýnē', de: 'Gerechtigkeit', group: 'vorsokratiker' },
  { id: 'genesis', gr: 'γένεσις', tr: 'génesis', de: 'Werden, Entstehen', group: 'vorsokratiker' },
  { id: 'demas', gr: 'δέμας', tr: 'démas', de: 'Körperbau, Gestalt', group: 'vorsokratiker' },
  { id: 'thnetos', gr: 'θνητός', tr: 'thnētós', de: 'sterblich', group: 'vorsokratiker' },
  { id: 'megas', gr: 'μέγας', tr: 'mégas', de: 'groß', group: 'vorsokratiker' },
  { id: 'polemos', gr: 'πόλεμος', tr: 'pólemos', de: 'Krieg', group: 'vorsokratiker' },
  { id: 'pater', gr: 'πατήρ', tr: 'patḗr', de: 'Vater', group: 'vorsokratiker' },
  { id: 'rhizomata', gr: 'ῥιζώματα', tr: 'rhizṓmata', de: 'Verwurzelungen', group: 'vorsokratiker' },
  { id: 'sphaira', gr: 'σφαῖρα', tr: 'sphaîra', de: 'Kugel, Ball', group: 'vorsokratiker' },
  { id: 'aletheia', gr: 'ἀλήθεια', tr: 'alḗtheia', de: 'Wahrheit', group: 'vorsokratiker' },
  { id: 'doxa', gr: 'δόξα', tr: 'dóxa', de: 'Meinung, Schein', group: 'vorsokratiker' },
  { id: 'hybris', gr: 'ὕβρις', tr: 'hýbris', de: 'Übermaß, Hochmut', group: 'vorsokratiker' },
  { id: 'physis', gr: 'φύσις', tr: 'phýsis', de: 'Wesen, Natur', group: 'vorsokratiker' },

  // ——— Platonisch (Frage 5) ———
  { id: 'phainomai', gr: 'φαίνομαι', tr: 'phaínomai', de: 'sich zeigen, erscheinen', group: 'platon' },
  { id: 'methexis', gr: 'μέθεξις', tr: 'méthexis', de: 'Teilhabe', group: 'platon' },
  { id: 'eidos', gr: 'εἶδος', tr: 'eîdos', de: 'Aussehen, Gestalt, Form, Gattung, Idee', group: 'platon' },
  { id: 'episteme', gr: 'ἐπιστήμη', tr: 'epistḗmē', de: 'Wissen, Können', group: 'platon' },
  { id: 'sophia', gr: 'σοφία', tr: 'sophía', de: 'Weisheit', group: 'platon' },
  { id: 'kinesis', gr: 'κίνησις', tr: 'kínēsis', de: 'Bewegung', group: 'platon' },
  { id: 'onoma', gr: 'ὄνομα', tr: 'ónoma', de: 'Name, Nomen', group: 'platon' },
  { id: 'organon', gr: 'ὄργανον', tr: 'órganon', de: 'Werkzeug', group: 'platon' },
  { id: 'idea', gr: 'ἰδέα', tr: 'idéa', de: 'Idee, Aussehen, Anblick', group: 'platon' },
  { id: 'paradeigma', gr: 'παράδειγμα', tr: 'parádeigma', de: 'Beispiel, Muster', group: 'platon' },
  { id: 'dialogos', gr: 'διάλογος', tr: 'diálogos', de: 'Gespräch, Unterhaltung', group: 'platon' },
  { id: 'demiourgos', gr: 'δημιουργός', tr: 'dēmiourgós', de: 'Handwerker, Demiurg', group: 'platon' },
  { id: 'psyche', gr: 'ψυχή', tr: 'psychḗ', de: 'Seele, Lebensprinzip', group: 'platon' },
  { id: 'auto', gr: 'αὐτό', tr: 'autó', de: 'Selbst', group: 'platon' },
  { id: 'noesis', gr: 'νόησις', tr: 'nóēsis', de: 'Denken (Tätigkeit)', group: 'platon' },
  { id: 'dianoia', gr: 'διάνοια', tr: 'diánoia', de: 'Denkvermögen, Verstand', group: 'platon' },
  { id: 'nous', gr: 'νοῦς', tr: 'noûs', de: 'Geist, Vernunft', group: 'platon' },
  { id: 'aisthesis', gr: 'αἴσθησις', tr: 'aísthēsis', de: 'Wahrnehmung, Empfindung, Sinn', group: 'platon' },
  { id: 'hypothesis', gr: 'ὑπόθεσις', tr: 'hypóthesis', de: 'Annahme', group: 'platon' },
  { id: 'paideia', gr: 'παιδεία', tr: 'paideía', de: 'Erziehung, Bildung', group: 'platon' },
  { id: 'paidia', gr: 'παιδιά', tr: 'paidiá', de: 'Spiel', group: 'platon' },
  { id: 'aporia', gr: 'ἀπορία', tr: 'aporía', de: 'Auswegslosigkeit', group: 'platon' },
  { id: 'graphe', gr: 'γραφή', tr: 'graphḗ', de: 'Schrift, Staatsklage', group: 'platon' },
  { id: 'diairesis', gr: 'διαίρεσις', tr: 'diaíresis', de: 'Trennung, Begriffsbestimmung', group: 'platon' },

  // ——— Aristotelisch (Frage 7) ———
  { id: 'kategoria', gr: 'κατηγορία', tr: 'katēgoría', de: 'Anklage, Aussage', group: 'aristoteles' },
  { id: 'entelecheia', gr: 'ἐντελέχεια', tr: 'entelécheia', de: '(vollendete) Wirklichkeit', group: 'aristoteles' },
  { id: 'hypokeimenon', gr: 'ὑποκείμενον', tr: 'hypokeímenon', de: 'das Zugrundeliegende', group: 'aristoteles' },
  { id: 'proairesis', gr: 'προαίρεσις', tr: 'proaíresis', de: 'Entscheidung, Vorsatz, freie Wahl', group: 'aristoteles' },
  { id: 'symbolon', gr: 'σύμβολον', tr: 'sýmbolon', de: 'Erkennungszeichen', group: 'aristoteles' },
  { id: 'hedone', gr: 'ἡδονή', tr: 'hēdonḗ', de: 'Lust, Vergnügen', group: 'aristoteles' },
  { id: 'metabole', gr: 'μεταβολή', tr: 'metabolḗ', de: 'Umschlag, Veränderung', group: 'aristoteles' },
  { id: 'hexis', gr: 'ἕξις', tr: 'héxis', de: 'Haltung, Zustand, Habitus', group: 'aristoteles' },
  { id: 'energeia', gr: 'ἐνέργεια', tr: 'enérgeia', de: 'Wirksamkeit, Tätigkeit', group: 'aristoteles' },
  { id: 'dynamis', gr: 'δύναμις', tr: 'dýnamis', de: 'Möglichkeit, Fähigkeit', group: 'aristoteles' },
  { id: 'ousia', gr: 'οὐσία', tr: 'ousía', de: 'Seiendheit, Wesen', group: 'aristoteles' },
  { id: 'telos', gr: 'τέλος', tr: 'télos', de: 'Ziel, Zweck', group: 'aristoteles' },
  { id: 'praxis', gr: 'πρᾶξις', tr: 'prâxis', de: 'Handlung, Tätigkeit', group: 'aristoteles' },
  { id: 'pragma', gr: 'πρᾶγμα', tr: 'prâgma', de: 'Handlung, Sache', group: 'aristoteles' },
  { id: 'poiotes', gr: 'ποιότης', tr: 'poiótēs', de: 'Qualität, „Wiebeschaffenheit"', group: 'aristoteles' },
  { id: 'pathema', gr: 'πάθημα', tr: 'páthēma', de: 'Erlebnis, Eindruck', group: 'aristoteles' },
  { id: 'hyle', gr: 'ὕλη', tr: 'hýlē', de: 'Holz, Materie', group: 'aristoteles' },
  { id: 'einai', gr: 'εἶναι', tr: 'eînai', de: '(zu) sein', group: 'aristoteles', note: 'Infinitiv' },

  // ——— Allgemeine Terminologie & Sachbegriffe ———
  { id: 'sophia2', gr: 'σοφία', tr: 'sophía', de: 'Klug-/Weisheit', group: 'allgemein' },
  { id: 'techne', gr: 'τέχνη', tr: 'téchnē', de: 'Kunstfertigkeit', group: 'allgemein' },
  { id: 'agathos', gr: 'ἀγαθός', tr: 'agathós', de: 'gut', group: 'allgemein' },
  { id: 'rhetor', gr: 'ῥήτωρ', tr: 'rhḗtōr', de: 'Redner', group: 'allgemein' },
  { id: 'aitia', gr: 'αἰτία, αἴτιον', tr: 'aitía, aítion', de: 'Grund, Ursache', group: 'allgemein' },
  { id: 'polis', gr: 'πόλις', tr: 'pólis', de: 'Stadt(staat)', group: 'allgemein' },
  { id: 'chronos', gr: 'χρόνος', tr: 'chrónos', de: 'Zeit', group: 'allgemein' },
  { id: 'zoon', gr: 'ζῷον', tr: 'zôon', de: 'Lebewesen, Tier', group: 'allgemein' },
  { id: 'anthropos', gr: 'ἄνθρωπος', tr: 'ánthrōpos', de: 'Mensch', group: 'allgemein' },
  { id: 'autarkeia', gr: 'αὐτάρκεια', tr: 'autárkeia', de: 'Selbstgenügsamkeit', group: 'allgemein' },
  { id: 'enkrateia', gr: 'ἐγκράτεια', tr: 'enkráteia', de: 'Selbstbeherrschung', group: 'allgemein' },
  { id: 'philosophos', gr: 'φιλόσοφος', tr: 'philósophos', de: 'die Weisheit liebend / Philosoph', group: 'allgemein' },
  { id: 'epithymia', gr: 'ἐπιθυμία', tr: 'epithymía', de: 'Neigung, Begierde', group: 'allgemein' },
  { id: 'exousia', gr: 'ἐξουσία', tr: 'exousía', de: 'Macht, Kompetenz', group: 'allgemein' },
  { id: 'elleipsis', gr: 'ἔλλειψις', tr: 'élleipsis', de: 'Mangel', group: 'allgemein' },
  { id: 'stasis', gr: 'στάσις', tr: 'stásis', de: 'Stehen, Stand, Bürgerkrieg', group: 'allgemein' },
  { id: 'mythos', gr: 'μῦθος', tr: 'mŷthos', de: 'Erzählung', group: 'allgemein' },
  { id: 'historia', gr: 'ἱστορία', tr: 'historía', de: 'Forschung, Erkenntnis, Geschichtsschreibung', group: 'allgemein' },
  { id: 'demos', gr: 'δῆμος', tr: 'dêmos', de: 'Volk', group: 'allgemein' },
  { id: 'didasko', gr: 'διδάσκω', tr: 'didáskō', de: '(zu) lehren', group: 'allgemein' },
  { id: 'rhythmos', gr: 'ῥυθμός', tr: 'rhythmós', de: 'Strom, Rhythmus', group: 'allgemein' },
  { id: 'synonymos', gr: 'συνώνυμος', tr: 'synṓnymos', de: 'gleichnamig', group: 'allgemein' },
  { id: 'diaphonia', gr: 'διαφωνία', tr: 'diaphōnía', de: 'Dissonanz', group: 'allgemein' },
  { id: 'phronesis', gr: 'φρόνησις', tr: 'phrónēsis', de: 'Klugheit', group: 'allgemein' },
  { id: 'klepto', gr: 'κλέπτω', tr: 'kléptō', de: 'stehlen', group: 'allgemein' },
  { id: 'moicheuo', gr: 'μοιχεύω', tr: 'moicheúō', de: 'ehebrechen', group: 'allgemein' },
  { id: 'apateuo', gr: 'ἀπατεύω', tr: 'apateúō', de: 'betrügen, täuschen', group: 'allgemein' },
  { id: 'anatithemi', gr: 'ἀνατίθημι', tr: 'anatíthēmi', de: 'aufbürden, anhängen', group: 'allgemein' },
  { id: 'tynchano', gr: 'τυγχάνω', tr: 'tynchánō', de: 'treffen', group: 'allgemein' },
  { id: 'lanthano', gr: 'λανθάνω', tr: 'lanthánō', de: 'sich verborgen halten / unbemerkt bleiben', group: 'allgemein' },
  { id: 'phronimos', gr: 'φρόνιμος', tr: 'phrónimos', de: 'besonnen, verständig', group: 'allgemein' },
  { id: 'hippos', gr: 'ἵππος', tr: 'híppos', de: 'Pferd', group: 'allgemein' },
  { id: 'anchinoia', gr: 'ἀγχίνοια', tr: 'anchínoia', de: 'Scharfsinn', group: 'allgemein' },
  { id: 'katalepsis', gr: 'κατάληψις', tr: 'katálēpsis', de: 'Erfassung', group: 'allgemein' },
  { id: 'syngramma', gr: 'σύγγραμμα', tr: 'sýngramma', de: 'Schrift, Abhandlung', group: 'allgemein' },
  { id: 'hosper', gr: 'ὥσπερ', tr: 'hṓsper', de: 'wie', group: 'allgemein' },
  { id: 'auletike', gr: 'αὐλητική', tr: 'aulētikḗ', de: 'Flötenspielkunst', group: 'allgemein' },
  { id: 'orchestra', gr: 'ὀρχήστρα', tr: 'orchḗstra', de: 'Tanzplatz im Theater', group: 'allgemein' },
  { id: 'syrinx', gr: 'σῦριγξ', tr: 'sûrinx', de: 'Panflöte', group: 'allgemein' },
  { id: 'baino', gr: 'βαίνω', tr: 'baínō', de: 'gehen', group: 'allgemein' },
  { id: 'kouros', gr: 'κοῦρος', tr: 'koûros', de: 'Jüngling', group: 'allgemein' },
  { id: 'hyios', gr: 'υἱός', tr: 'hyiós', de: 'der Sohn', group: 'allgemein' },
  { id: 'hamartia', gr: 'ἁμαρτία', tr: 'hamartía', de: 'Fehler, Verfehlung', group: 'allgemein', note: 'Spiritus asper -> h' },
  { id: 'hellas', gr: 'Ἑλλάς', tr: 'Hellás', de: 'Griechenland', group: 'allgemein', note: 'Spiritus asper -> h' },
  { id: 'hairesis', gr: 'αἵρεσις', tr: 'haíresis', de: 'Wahl, Richtung, Schule', group: 'allgemein', note: 'Spiritus asper auf Diphthong' },
  { id: 'eudaimonia', gr: 'εὐδαιμονία', tr: 'eudaimonía', de: 'Glückseligkeit, gutes Leben', group: 'allgemein', note: 'ευ -> eu' },
  { id: 'angello', gr: 'ἀγγέλλω', tr: 'angélō', de: 'melden, verkünden', group: 'allgemein', note: 'γγ -> ng' },
  { id: 'dithyrambos', gr: 'διθύραμβος', tr: 'dithýrambos', de: 'Dithyrambus', group: 'allgemein' },
  { id: 'knizo', gr: 'κνίζω', tr: 'knízō', de: 'kratzen, reizen', group: 'allgemein' },
  { id: 'rhine', gr: 'ῥίνη', tr: 'rhínē', de: 'Feile', group: 'allgemein', note: 'initiales ρ -> rh' },
  { id: 'hymnos', gr: 'ὕμνος', tr: 'hýmnos', de: 'Hymne, Lied', group: 'allgemein' },
  { id: 'psogos', gr: 'ψόγος', tr: 'psógos', de: 'Tadel, Schimpf', group: 'allgemein' },
  { id: 'tragodia', gr: 'τραγῳδία', tr: 'tragōdía', de: 'Tragödie', group: 'allgemein' },
  { id: 'xuthos', gr: 'ξουθός', tr: 'xuthós', de: 'goldgelb, flink', group: 'allgemein' },
  { id: 'metabalein', gr: 'μεταβαλεῖν', tr: 'metabaleîn', de: 'umwenden, verändern', group: 'allgemein' },
  { id: 'zanklon', gr: 'ζάγκλον', tr: 'zánklon', de: 'Sichel', group: 'allgemein', note: 'γ vor κ -> n' },
  { id: 'dekapēchys', gr: 'δεκάπηχυς', tr: 'dekápēchys', de: 'zehn Ellen lang', group: 'allgemein' },
  { id: 'on', gr: 'ὄν', tr: 'ón', de: 'seiend, das Seiende', group: 'allgemein', note: 'Partizip Präsens zu εἰμί' },
  { id: 'noema', gr: 'νόημα', tr: 'nóēma', de: 'Gedanke als Ergebnis', group: 'allgemein' },
  { id: 'noumena', gr: 'νοούμενα', tr: 'noúmena', de: 'das Gedachte, Denkinhalt', group: 'allgemein' },
  { id: 'peirar', gr: 'πεῖραρ', tr: 'peîrar', de: 'Grenze', group: 'allgemein' },
  { id: 'tisis', gr: 'τίσις', tr: 'tísis', de: 'Buße, Strafe', group: 'allgemein' },
  { id: 'taxis', gr: 'τάξις', tr: 'táxis', de: 'Ordnung, Anordnung', group: 'allgemein' },
  { id: 'adikia', gr: 'ἀδικία', tr: 'adikía', de: 'Unrecht', group: 'allgemein' },
  { id: 'allos', gr: 'ἄλλος', tr: 'állos', de: 'anderer, verschieden', group: 'allgemein' },
  { id: 'kalos', gr: 'καλός', tr: 'kalós', de: 'schön, gut', group: 'allgemein' },
  { id: 'kata-tauta', gr: 'κατὰ ταὐτά', tr: 'katà tautá', de: 'gemäß demselben', group: 'allgemein' },
  { id: 'prospoiesis', gr: 'προσποίησις', tr: 'prospoíēsis', de: 'Verstärkung, Anspruch, Anmaßung', group: 'allgemein' },
  { id: 'synkephalaioo', gr: 'συγκεφαλαιόω', tr: 'synkephalaióō', de: 'zusammenfassen', group: 'allgemein' },
  { id: 'hyperbole', gr: 'ὑπερβολή', tr: 'hyperbolḗ', de: 'Übersteigung, Übermaß', group: 'allgemein' },
  { id: 'hyperballo', gr: 'ὑπερβάλλω', tr: 'hyper-bállō', de: 'übertreffen', group: 'allgemein' },
  { id: 'gignomai', gr: 'γίγνομαι', tr: 'gígnomai', de: 'werden', group: 'allgemein', note: 'Deponens, Medium/Passiv-Form' },
  { id: 'axynetos', gr: 'ἀξύνετος', tr: 'axýnetos', de: 'unverständig', group: 'allgemein' },
  { id: 'aei', gr: 'ἀεί', tr: 'aeí', de: 'immer', group: 'allgemein' },
  { id: 'exeurisko', gr: 'ἐξευρίσκω', tr: 'exeurískō', de: 'herausfinden, ausfindig machen', group: 'allgemein' },
  { id: 'hodos', gr: 'ὁδός', tr: 'hodós', de: 'Weg', group: 'allgemein' },
  { id: 'bathys', gr: 'βαθύς', tr: 'bathýs', de: 'tief', group: 'allgemein' },
  { id: 'houto', gr: 'οὕτω', tr: 'hoútō', de: 'so, auf diese Weise', group: 'allgemein' },
  { id: 'echo', gr: 'ἔχω', tr: 'échō', de: 'haben, halten', group: 'allgemein' },
  { id: 'pas', gr: 'πᾶς', tr: 'pâs', de: 'jeder, ganz, alles', group: 'allgemein' },
  { id: 'lyo', gr: 'λύω', tr: 'lýō', de: 'lösen, befreien', group: 'allgemein' },
  { id: 'lyomai', gr: 'λύομαι', tr: 'lýomai', de: 'ich befreie mich / ich werde befreit', group: 'allgemein' },
  { id: 'aichmalotos', gr: 'αἰχμάλωτος', tr: 'aichmálōtos', de: 'Gefangener', group: 'allgemein' },
  { id: 'paideuo', gr: 'παιδεύω', tr: 'paideúō', de: 'erziehen, unterrichten', group: 'allgemein' },
  { id: 'pais', gr: 'παῖς', tr: 'paîs', de: 'Kind', group: 'allgemein' },
  { id: 'didaskalos', gr: 'διδάσκαλος', tr: 'didáskalos', de: 'Lehrer', group: 'allgemein' },
  { id: 'basileus', gr: 'βασιλεύς', tr: 'basileús', de: 'König', group: 'allgemein' },
  { id: 'deiknymi', gr: 'δείκνυμι', tr: 'deíknymi', de: 'zeigen, nachweisen, erweisen', group: 'allgemein' },
  { id: 'edeixe', gr: 'ἔδειξε', tr: 'édeixe', de: 'er zeigte / erwies', group: 'allgemein', note: 'Aorist zu δείκνυμι' },
  { id: 'poieo', gr: 'ποιέω', tr: 'poiéō', de: 'machen, tun', group: 'allgemein' },
  { id: 'epoiese', gr: 'ἐποίησε', tr: 'epoíēse', de: 'er machte', group: 'allgemein', note: 'Aorist zu ποιέω' },
  { id: 'doulos', gr: 'δοῦλος', tr: 'doûlos', de: 'Sklave', group: 'allgemein' },
  { id: 'eleutheros', gr: 'ἐλεύθερος', tr: 'eleútheros', de: 'frei', group: 'allgemein' },
  { id: 'men-de', gr: 'μέν ... δέ', tr: 'mén ... dé', de: 'die einen ... die anderen; zwar ... aber', group: 'allgemein' },
  { id: 'epieikeuo', gr: 'ἐπιεικεύω', tr: 'epieikeúō', de: 'nachsichtig sein / werden', group: 'allgemein' },
  { id: 'anankastos', gr: 'ἀναγκαστός', tr: 'anankastós', de: 'erzwungen', group: 'allgemein' },
  { id: 'ankyle', gr: 'ἀγκύλη', tr: 'ankýlē', de: 'Krümmung', group: 'allgemein' },
  { id: 'embaino', gr: 'ἐμβαίνω', tr: 'embaínō', de: 'hineinsteigen', group: 'allgemein' },
  { id: 'potamos', gr: 'ποταμός', tr: 'potamós', de: 'Fluss', group: 'allgemein' },
  { id: 'autos', gr: 'αὐτός', tr: 'autós', de: 'selbst, derselbe', group: 'allgemein' },
  { id: 'te-kai', gr: 'τε καί', tr: 'te kaí', de: 'und, auch', group: 'allgemein' },
  { id: 'ouk', gr: 'οὐκ', tr: 'ouk', de: 'nicht', group: 'allgemein' },
  { id: 'eimen', gr: 'εἶμεν', tr: 'eîmen', de: 'wir sind', group: 'allgemein', note: 'ionische Form zu ἐσμέν' },
  { id: 'heis', gr: 'εἷς', tr: 'heîs', de: 'ein', group: 'allgemein' },
  { id: 'en-under', gr: 'ἔν', tr: 'én', de: 'unter', group: 'allgemein' },
  { id: 'megistos', gr: 'μέγιστος', tr: 'mégistos', de: 'größter', group: 'allgemein' },
  { id: 'outi', gr: 'οὔτι', tr: 'oúti', de: 'gar nicht', group: 'allgemein' },
  { id: 'homoios', gr: 'ὅμοιος', tr: 'hómoios', de: 'ähnlich', group: 'allgemein' },
  { id: 'oude', gr: 'οὐδέ', tr: 'oudé', de: 'und nicht, noch', group: 'allgemein' },
  { id: 'eirēke', gr: 'εἴρηκε', tr: 'eírēke', de: 'er hat gesagt', group: 'allgemein', note: 'Perfekt zu λέγω' },
  { id: 'ex-hon', gr: 'ἐξ ὧν', tr: 'ex hôn', de: 'aus welchen', group: 'allgemein' },
  { id: 'tauta', gr: 'ταῦτα', tr: 'taûta', de: 'diese Dinge', group: 'allgemein' },
  { id: 'didomi', gr: 'δίδωμι', tr: 'dídōmi', de: 'geben', group: 'allgemein' },
  { id: 'allelon', gr: 'ἀλλήλων', tr: 'allḗlōn', de: 'einander', group: 'allgemein' },
  { id: 'hoi-ontes', gr: 'οἱ ὄντες', tr: 'hoi óntes', de: 'die Seienden', group: 'allgemein' },
  { id: 'iatromantis', gr: 'ἰατρόμαντις', tr: 'iatrómantis', de: 'Heiler, Seherarzt', group: 'allgemein' },
  { id: 'enchos', gr: 'ἔγχος', tr: 'énchos', de: 'Speer', group: 'allgemein' },
  { id: 'homeros', gr: 'Ὅμηρος', tr: 'Hómēros', de: 'Homer', group: 'allgemein' },
  { id: 'hesiodos', gr: 'Ἡσίοδος', tr: 'Hēsíodos', de: 'Hesiod', group: 'allgemein' },
  { id: 'hossa', gr: 'ὅσσα', tr: 'hóssa', de: 'wieviel, so viel wie', group: 'allgemein' },
  { id: 'para', gr: 'παρά', tr: 'pará', de: 'bei, neben; mit Dativ lokal bei', group: 'allgemein' },
  { id: 'oneidea', gr: 'ὀνείδεα', tr: 'oneídea', de: 'Tadel, Schmach', group: 'allgemein' },
  { id: 'panta', gr: 'πάντα', tr: 'pánta', de: 'alles', group: 'allgemein' },
  { id: 'epikanchalao', gr: 'ἐπικαγχαλάω', tr: 'epikanchaláō', de: 'darauf stolz sein', group: 'allgemein' },
  { id: 'proschraomai', gr: 'προσχράομαι', tr: 'proschráomai', de: 'zu Hilfe nehmen', group: 'allgemein' },
  { id: 'lyperos', gr: 'λυπηρός', tr: 'lypērós', de: 'betrübend', group: 'allgemein' },
  { id: 'presbeia', gr: 'πρεσβεία', tr: 'presbeía', de: 'Würde, Recht des Älteren', group: 'allgemein' },
  { id: 'thateron', gr: 'θάτερον', tr: 'tháteron', de: 'das Verschiedene', group: 'allgemein' },
  { id: 'pherekydes', gr: 'Φερεκύδης', tr: 'Pherekýdēs', de: 'Pherekydes', group: 'allgemein' },
  { id: 'hellanikos', gr: 'Ἑλλάνικος', tr: 'Hellánikos', de: 'Hellanikos', group: 'allgemein' },
  { id: 'daimachos', gr: 'Δαΐμαχος', tr: 'Daímachos', de: 'Daimachos', group: 'allgemein' },
  { id: 'philon', gr: 'Φίλων', tr: 'Phílōn', de: 'Philon', group: 'allgemein' },
  { id: 'solon', gr: 'Σόλων', tr: 'Sólōn', de: 'Solon', group: 'allgemein' },
  { id: 'epimenides', gr: 'Ἐπιμενίδης', tr: 'Epimenídēs', de: 'Epimenides', group: 'allgemein' },
  { id: 'kleoboulos', gr: 'Κλεόβουλος', tr: 'Kleóboulos', de: 'Kleoboulos', group: 'allgemein' },
  { id: 'anaxagoras', gr: 'Ἀναξαγόρας', tr: 'Anaxagóras', de: 'Anaxagoras', group: 'allgemein' },
  { id: 'peisistratos', gr: 'Πεισίστρατος', tr: 'Peisístratos', de: 'Peisistratos', group: 'allgemein' },
  { id: 'edoxe', gr: 'ἔδοξε', tr: 'édoxe', de: 'es schien', group: 'allgemein', note: 'Aorist zu δοκέω' },
  { id: 'dokeo', gr: 'δοκέω', tr: 'dokéō', de: 'meinen, scheinen', group: 'allgemein' },
  { id: 'moi', gr: 'μοι', tr: 'moi', de: 'mir', group: 'allgemein' },
  { id: 'chrenai', gr: 'χρῆναι', tr: 'chrênai', de: 'notwendig sein', group: 'allgemein' },
  { id: 'chre', gr: 'χρή', tr: 'chrḗ', de: 'es ist nötig, man muss', group: 'allgemein' },
  { id: 'katapheugo', gr: 'καταφεύγω', tr: 'katapheúgō', de: 'hinfliehen, Zuflucht nehmen', group: 'allgemein' },
  { id: 'skopeo', gr: 'σκοπέω', tr: 'skopéō', de: 'ausspähen, untersuchen, prüfen', group: 'allgemein' },
  { id: 'ekeinois', gr: 'ἐκείνοις', tr: 'ekeínois', de: 'in ihnen, jenen', group: 'allgemein' },
  { id: 'propideion', gr: 'προπιδεῖον', tr: 'propideîon', de: 'nachbessern', group: 'allgemein' },
  { id: 'grammatodidaskaleion', gr: 'γραμματοδιδασκαλεῖον', tr: 'grammatodidaskaleîon', de: 'Grundschule', group: 'allgemein' },
  { id: 'epikrateia', gr: 'ἐπικράτεια', tr: 'epikráteia', de: 'Oberherrschaft', group: 'allgemein' },
  { id: 'opsartytes', gr: 'ὀψαρτυτής', tr: 'opsartytḗs', de: 'Speisenzubereiter', group: 'allgemein' },
  { id: 'ichthyoeis', gr: 'ἰχθυόεις', tr: 'ichthyóeis', de: 'fischig, fischreich', group: 'allgemein' },
  { id: 'epicheireo', gr: 'ἐπιχειρέω', tr: 'epicheiréō', de: 'versuchen, unternehmen', group: 'allgemein' },
  { id: 'kyoumene', gr: 'κυουμένη', tr: 'kyouménē', de: 'schwanger, seiend', group: 'allgemein' },
  { id: 'ankon', gr: 'ἀγκών', tr: 'ankṓn', de: 'Ellenbogen', group: 'allgemein' },
  { id: 'scholastikos', gr: 'σχολαστικός', tr: 'scholastikós', de: 'müßig, den Wissenschaften gewidmet', group: 'allgemein' },
  { id: 'tachypnoia', gr: 'ταχύπνοια', tr: 'tachýpnoia', de: 'schnelles Atemholen', group: 'allgemein' },
  { id: 'erchomai', gr: 'ἔρχομαι', tr: 'érchomai', de: 'gehen, kommen', group: 'allgemein' },
  { id: 'epideiknymi', gr: 'ἐπιδείκνυμι', tr: 'epideíknymi', de: 'zeigen, vorführen', group: 'allgemein' },
  { id: 'palin', gr: 'πάλιν', tr: 'pálin', de: 'wieder, zurück', group: 'allgemein' },
  { id: 'hypothemenos', gr: 'ὑποθέμενος', tr: 'hypothémenos', de: 'voraussetzend', group: 'allgemein' },
  { id: 'kath-hauto', gr: "καθ' αὑτό", tr: "kath' hautó", de: 'gemäß sich selbst, an sich', group: 'allgemein' },
  { id: 'plen', gr: 'πλήν', tr: 'plḗn', de: 'außer', group: 'allgemein' },
  { id: 'dia', gr: 'διά', tr: 'diá', de: 'durch, wegen', group: 'allgemein' },
  { id: 'hen', gr: 'ἕν', tr: 'hén', de: 'eins', group: 'allgemein' },
  { id: 'dioti', gr: 'διότι', tr: 'dióti', de: 'weil', group: 'allgemein' },
  { id: 'metecho', gr: 'μετέχω', tr: 'metéchō', de: 'Anteil haben', group: 'allgemein' },
  { id: 'ekeinos', gr: 'ἐκεῖνος', tr: 'ekeînos', de: 'jener', group: 'allgemein' },
  { id: 'choreo', gr: 'χωρέω', tr: 'chōréō', de: 'weichen, gehen', group: 'allgemein' },
]
