import type { Vocab } from './types'

// Complete philosophical vocabulary from the course (Einheit 1–10 + Muster).
// group reflects the exam grouping where the term is explicitly listed:
//   vorsokratiker = Frage 3 / frühgriechisch · platon = Frage 5 · aristoteles = Frage 7
//   allgemein = general terminology & transcription vocabulary.

export const VOCAB: Vocab[] = [
  // ——— Frühgriechisch / Vorsokratiker (Frage 3) ———
  { id: 'noein', gr: 'νοεῖν', tr: 'noeîn', de: 'denken', group: 'vorsokratiker', note: 'Inf. zu νοέω' },
  { id: 'dike', gr: 'δίκη', tr: 'díkē', de: 'Recht', group: 'vorsokratiker' },
  { id: 'arche', gr: 'ἀρχή', tr: 'archḗ', de: 'Anfang, Urgrund', group: 'vorsokratiker' },
  { id: 'moira', gr: 'μοῖρα', tr: 'moîra', de: 'Teil, Anteil, Los, Schicksal', group: 'vorsokratiker' },
  { id: 'theos', gr: 'θεός', tr: 'theós', de: 'Gott', group: 'vorsokratiker' },
  { id: 'rhema', gr: 'ῥῆμα', tr: 'rhêma', de: 'Wort, Verbum', group: 'vorsokratiker' },
  { id: 'hydor', gr: 'ὕδωρ', tr: 'hýdōr', de: 'Wasser', group: 'vorsokratiker' },
  { id: 'phora', gr: 'φορά', tr: 'phorá', de: 'Bewegung, das (Sich-)Tragen', group: 'vorsokratiker' },
  { id: 'phthora', gr: 'φθορά', tr: 'phthorá', de: 'Zerstörung, Vergehen', group: 'vorsokratiker' },
  { id: 'apeiron', gr: 'ἄπειρον', tr: 'ápeiron', de: 'das Unendliche', group: 'vorsokratiker' },
  { id: 'chreon', gr: 'χρεών', tr: 'chreṓn', de: 'Notwendigkeit, Schicksal', group: 'vorsokratiker' },
  { id: 'logos', gr: 'λόγος', tr: 'lógos', de: 'Rede, Wort, Argument, Vernunft', group: 'vorsokratiker', note: 'vieldeutiger Begriff' },
  { id: 'kosmos', gr: 'κόσμος', tr: 'kósmos', de: 'Ordnung, Schmuck, Universum', group: 'vorsokratiker' },
  { id: 'arete', gr: 'ἀρετή', tr: 'aretḗ', de: 'Vortrefflichkeit, Bestform, Tugend', group: 'vorsokratiker' },
  { id: 'elpis', gr: 'ἐλπίς', tr: 'elpís', de: 'Hoffnung', group: 'vorsokratiker' },
  { id: 'ananke', gr: 'ἀνάγκη', tr: 'anánkē', de: 'Zwang, Notwendigkeit', group: 'vorsokratiker' },
  { id: 'dikaiosyne', gr: 'δικαιοσύνη', tr: 'dikaiosýnē', de: 'Gerechtigkeit', group: 'vorsokratiker' },
  { id: 'genesis', gr: 'γένεσις', tr: 'génesis', de: 'Werden, Entstehen', group: 'vorsokratiker' },
  { id: 'demas', gr: 'δέμας', tr: 'démas', de: 'Körperbau, Gestalt', group: 'vorsokratiker' },
  { id: 'thnetos', gr: 'θνητός', tr: 'thnētós', de: 'sterblich', group: 'vorsokratiker' },
  { id: 'megas', gr: 'μέγας', tr: 'mégas', de: 'groß', group: 'vorsokratiker' },
  { id: 'polemos', gr: 'πόλεμος', tr: 'pólemos', de: 'Krieg', group: 'vorsokratiker' },
  { id: 'pater', gr: 'πατήρ', tr: 'patḗr', de: 'Vater', group: 'vorsokratiker' },
  { id: 'rhizomata', gr: 'ῥιζώματα', tr: 'rhizṓmata', de: 'Verwurzelungen', group: 'vorsokratiker' },
  { id: 'sphaira', gr: 'σφαῖρα', tr: 'sphaîra', de: 'Kugel, Ball', group: 'vorsokratiker' },
  { id: 'aletheia', gr: 'ἀλήθεια', tr: 'alḗtheia', de: 'Wahrheit', group: 'vorsokratiker' },
  { id: 'doxa', gr: 'δόξα', tr: 'dóxa', de: 'Meinung, Schein', group: 'vorsokratiker' },
  { id: 'hybris', gr: 'ὕβρις', tr: 'hýbris', de: 'Übermaß, Hochmut', group: 'vorsokratiker' },
  { id: 'physis', gr: 'φύσις', tr: 'phýsis', de: 'Wesen, Natur', group: 'vorsokratiker' },

  // ——— Platonisch (Frage 5) ———
  { id: 'phainomai', gr: 'φαίνομαι', tr: 'phaínomai', de: 'sich zeigen, erscheinen', group: 'platon' },
  { id: 'methexis', gr: 'μέθεξις', tr: 'méthexis', de: 'Teilhabe', group: 'platon' },
  { id: 'eidos', gr: 'εἶδος', tr: 'eîdos', de: 'Aussehen, Gestalt, Form, Gattung, Idee', group: 'platon' },
  { id: 'episteme', gr: 'ἐπιστήμη', tr: 'epistḗmē', de: 'Wissen, Können', group: 'platon' },
  { id: 'sophia', gr: 'σοφία', tr: 'sophía', de: 'Weisheit', group: 'platon' },
  { id: 'kinesis', gr: 'κίνησις', tr: 'kínēsis', de: 'Bewegung', group: 'platon' },
  { id: 'onoma', gr: 'ὄνομα', tr: 'ónoma', de: 'Name, Nomen', group: 'platon' },
  { id: 'organon', gr: 'ὄργανον', tr: 'órganon', de: 'Werkzeug', group: 'platon' },
  { id: 'idea', gr: 'ἰδέα', tr: 'idéa', de: 'Idee, Aussehen, Anblick', group: 'platon' },
  { id: 'paradeigma', gr: 'παράδειγμα', tr: 'parádeigma', de: 'Beispiel, Muster', group: 'platon' },
  { id: 'dialogos', gr: 'διάλογος', tr: 'diálogos', de: 'Gespräch, Unterhaltung', group: 'platon' },
  { id: 'demiourgos', gr: 'δημιουργός', tr: 'dēmiourgós', de: 'Handwerker, Demiurg', group: 'platon' },
  { id: 'psyche', gr: 'ψυχή', tr: 'psychḗ', de: 'Seele, Lebensprinzip', group: 'platon' },
  { id: 'auto', gr: 'αὐτό', tr: 'autó', de: 'Selbst', group: 'platon' },
  { id: 'noesis', gr: 'νόησις', tr: 'nóēsis', de: 'Denken (Tätigkeit)', group: 'platon' },
  { id: 'dianoia', gr: 'διάνοια', tr: 'diánoia', de: 'Denkvermögen, Verstand', group: 'platon' },
  { id: 'nous', gr: 'νοῦς', tr: 'noûs', de: 'Geist, Vernunft', group: 'platon' },
  { id: 'aisthesis', gr: 'αἴσθησις', tr: 'aísthēsis', de: 'Wahrnehmung, Empfindung, Sinn', group: 'platon' },
  { id: 'hypothesis', gr: 'ὑπόθεσις', tr: 'hypóthesis', de: 'Annahme', group: 'platon' },
  { id: 'paideia', gr: 'παιδεία', tr: 'paideía', de: 'Erziehung, Bildung', group: 'platon' },
  { id: 'paidia', gr: 'παιδιά', tr: 'paidiá', de: 'Spiel', group: 'platon' },
  { id: 'aporia', gr: 'ἀπορία', tr: 'aporía', de: 'Auswegslosigkeit', group: 'platon' },
  { id: 'graphe', gr: 'γραφή', tr: 'graphḗ', de: 'Schrift, Staatsklage', group: 'platon' },
  { id: 'diairesis', gr: 'διαίρεσις', tr: 'diaíresis', de: 'Trennung, Begriffsbestimmung', group: 'platon' },

  // ——— Aristotelisch (Frage 7) ———
  { id: 'kategoria', gr: 'κατηγορία', tr: 'katēgoría', de: 'Anklage, Aussage', group: 'aristoteles' },
  { id: 'entelecheia', gr: 'ἐντελέχεια', tr: 'entelécheia', de: '(vollendete) Wirklichkeit', group: 'aristoteles' },
  { id: 'hypokeimenon', gr: 'ὑποκείμενον', tr: 'hypokeímenon', de: 'das Zugrundeliegende', group: 'aristoteles' },
  { id: 'proairesis', gr: 'προαίρεσις', tr: 'proaíresis', de: 'Entscheidung, Vorsatz, freie Wahl', group: 'aristoteles' },
  { id: 'symbolon', gr: 'σύμβολον', tr: 'sýmbolon', de: 'Erkennungszeichen', group: 'aristoteles' },
  { id: 'hedone', gr: 'ἡδονή', tr: 'hēdonḗ', de: 'Lust, Vergnügen', group: 'aristoteles' },
  { id: 'metabole', gr: 'μεταβολή', tr: 'metabolḗ', de: 'Umschlag, Veränderung', group: 'aristoteles' },
  { id: 'hexis', gr: 'ἕξις', tr: 'héxis', de: 'Haltung, Zustand, Habitus', group: 'aristoteles' },
  { id: 'energeia', gr: 'ἐνέργεια', tr: 'enérgeia', de: 'Wirksamkeit, Tätigkeit', group: 'aristoteles' },
  { id: 'dynamis', gr: 'δύναμις', tr: 'dýnamis', de: 'Möglichkeit, Fähigkeit', group: 'aristoteles' },
  { id: 'ousia', gr: 'οὐσία', tr: 'ousía', de: 'Seiendheit, Wesen', group: 'aristoteles' },
  { id: 'telos', gr: 'τέλος', tr: 'télos', de: 'Ziel, Zweck', group: 'aristoteles' },
  { id: 'praxis', gr: 'πρᾶξις', tr: 'prâxis', de: 'Handlung, Tätigkeit', group: 'aristoteles' },
  { id: 'pragma', gr: 'πρᾶγμα', tr: 'prâgma', de: 'Handlung, Sache', group: 'aristoteles' },
  { id: 'poiotes', gr: 'ποιότης', tr: 'poiótēs', de: 'Qualität, „Wiebeschaffenheit"', group: 'aristoteles' },
  { id: 'pathema', gr: 'πάθημα', tr: 'páthēma', de: 'Erlebnis, Eindruck', group: 'aristoteles' },
  { id: 'hyle', gr: 'ὕλη', tr: 'hýlē', de: 'Holz, Materie', group: 'aristoteles' },
  { id: 'einai', gr: 'εἶναι', tr: 'eînai', de: '(zu) sein', group: 'aristoteles', note: 'Infinitiv' },

  // ——— Allgemeine Terminologie & Sachbegriffe ———
  { id: 'sophia2', gr: 'σοφία', tr: 'sophía', de: 'Klug-/Weisheit', group: 'allgemein' },
  { id: 'techne', gr: 'τέχνη', tr: 'téchnē', de: 'Kunstfertigkeit', group: 'allgemein' },
  { id: 'agathos', gr: 'ἀγαθός', tr: 'agathós', de: 'gut', group: 'allgemein' },
  { id: 'rhetor', gr: 'ῥήτωρ', tr: 'rhḗtōr', de: 'Redner', group: 'allgemein' },
  { id: 'aitia', gr: 'αἰτία, αἴτιον', tr: 'aitía, aítion', de: 'Grund, Ursache', group: 'allgemein' },
  { id: 'polis', gr: 'πόλις', tr: 'pólis', de: 'Stadt(staat)', group: 'allgemein' },
  { id: 'chronos', gr: 'χρόνος', tr: 'chrónos', de: 'Zeit', group: 'allgemein' },
  { id: 'zoon', gr: 'ζῷον', tr: 'zôon', de: 'Lebewesen, Tier', group: 'allgemein' },
  { id: 'anthropos', gr: 'ἄνθρωπος', tr: 'ánthrōpos', de: 'Mensch', group: 'allgemein' },
  { id: 'autarkeia', gr: 'αὐτάρκεια', tr: 'autárkeia', de: 'Selbstgenügsamkeit', group: 'allgemein' },
  { id: 'enkrateia', gr: 'ἐγκράτεια', tr: 'enkráteia', de: 'Selbstbeherrschung', group: 'allgemein' },
  { id: 'philosophos', gr: 'φιλόσοφος', tr: 'philósophos', de: 'die Weisheit liebend / Philosoph', group: 'allgemein' },
  { id: 'epithymia', gr: 'ἐπιθυμία', tr: 'epithymía', de: 'Neigung, Begierde', group: 'allgemein' },
  { id: 'exousia', gr: 'ἐξουσία', tr: 'exousía', de: 'Macht, Kompetenz', group: 'allgemein' },
  { id: 'elleipsis', gr: 'ἔλλειψις', tr: 'élleipsis', de: 'Mangel', group: 'allgemein' },
  { id: 'stasis', gr: 'στάσις', tr: 'stásis', de: 'Stehen, Stand, Bürgerkrieg', group: 'allgemein' },
  { id: 'mythos', gr: 'μῦθος', tr: 'mŷthos', de: 'Erzählung', group: 'allgemein' },
  { id: 'historia', gr: 'ἱστορία', tr: 'historía', de: 'Forschung, Erkenntnis, Geschichtsschreibung', group: 'allgemein' },
  { id: 'demos', gr: 'δῆμος', tr: 'dêmos', de: 'Volk', group: 'allgemein' },
  { id: 'didasko', gr: 'διδάσκω', tr: 'didáskō', de: '(zu) lehren', group: 'allgemein' },
  { id: 'rhythmos', gr: 'ῥυθμός', tr: 'rhythmós', de: 'Strom, Rhythmus', group: 'allgemein' },
  { id: 'synonymos', gr: 'συνώνυμος', tr: 'synṓnymos', de: 'gleichnamig', group: 'allgemein' },
  { id: 'diaphonia', gr: 'διαφωνία', tr: 'diaphōnía', de: 'Dissonanz', group: 'allgemein' },
  { id: 'phronesis', gr: 'φρόνησις', tr: 'phrónēsis', de: 'Klugheit', group: 'allgemein' },
  { id: 'klepto', gr: 'κλέπτω', tr: 'kléptō', de: 'stehlen', group: 'allgemein' },
  { id: 'moicheuo', gr: 'μοιχεύω', tr: 'moicheúō', de: 'ehebrechen', group: 'allgemein' },
  { id: 'apateuo', gr: 'ἀπατεύω', tr: 'apateúō', de: 'betrügen, täuschen', group: 'allgemein' },
  { id: 'anatithemi', gr: 'ἀνατίθημι', tr: 'anatíthēmi', de: 'aufbürden, anhängen', group: 'allgemein' },
  { id: 'tynchano', gr: 'τυγχάνω', tr: 'tynchánō', de: 'treffen', group: 'allgemein' },
  { id: 'lanthano', gr: 'λανθάνω', tr: 'lanthánō', de: 'sich verborgen halten / unbemerkt bleiben', group: 'allgemein' },
  { id: 'phronimos', gr: 'φρόνιμος', tr: 'phrónimos', de: 'besonnen, verständig', group: 'allgemein' },
  { id: 'hippos', gr: 'ἵππος', tr: 'híppos', de: 'Pferd', group: 'allgemein' },
  { id: 'anchinoia', gr: 'ἀγχίνοια', tr: 'anchínoia', de: 'Scharfsinn', group: 'allgemein' },
  { id: 'katalepsis', gr: 'κατάληψις', tr: 'katálēpsis', de: 'Erfassung', group: 'allgemein' },
  { id: 'syngramma', gr: 'σύγγραμμα', tr: 'sýngramma', de: 'Schrift, Abhandlung', group: 'allgemein' },
  { id: 'hosper', gr: 'ὥσπερ', tr: 'hṓsper', de: 'wie', group: 'allgemein' },
  { id: 'auletike', gr: 'αὐλητική', tr: 'aulētikḗ', de: 'Flötenspielkunst', group: 'allgemein' },
  { id: 'orchestra', gr: 'ὀρχήστρα', tr: 'orchḗstra', de: 'Tanzplatz im Theater', group: 'allgemein' },
  { id: 'syrinx', gr: 'σῦριγξ', tr: 'sûrinx', de: 'Panflöte', group: 'allgemein' },
  { id: 'baino', gr: 'βαίνω', tr: 'baínō', de: 'gehen', group: 'allgemein' },
  { id: 'kouros', gr: 'κοῦρος', tr: 'koûros', de: 'Jüngling', group: 'allgemein' },
  { id: 'hyios', gr: 'υἱός', tr: 'hyiós', de: 'der Sohn', group: 'allgemein' },
]
